'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import Header from '../components/Header';
import {api,money} from '../lib';
export default function Admin(){
 const [ads,setAds]=useState<any[]>([]),[reports,setReports]=useState<any[]>([]),[orders,setOrders]=useState<any[]>([]),[promotions,setPromotions]=useState<any[]>([]),[verifications,setVerifications]=useState<any[]>([]),[tab,setTab]=useState('ads');
 useEffect(()=>{const x=localStorage.getItem('minify_user');if(!x){location.href='/login';return}const u=JSON.parse(x);if(!['ADMIN','MODERATOR'].includes(u.role)){location.href='/dashboard';return}Promise.all([api('/admin/pending-ads'),api('/admin/reports'),api('/admin/orders'),api('/admin/promotions'),api('/admin/verification-requests')]).then(([a,r,o,p,v])=>{setAds(a);setReports(r);setOrders(o);setPromotions(p);setVerifications(v)}).catch(()=>{})},[]);
 async function status(id:string,s:string){let note:string|null=null;if(s==='REJECTED'){note=prompt('Reason for rejection (seller will see this):','Please improve the advert title, description or photos.')?.trim()||null;if(!note)return}try{await api('/admin/ads/'+id+'/status',{method:'PATCH',body:JSON.stringify({status:s,note})});setAds(x=>x.filter(a=>a.id!==id))}catch(e:any){alert(e.message||'Could not update advert.')}}
 async function resolve(id:string){await api('/admin/reports/'+id+'/resolve',{method:'PATCH'});setReports(x=>x.filter(r=>r.id!==id))}
 async function orderStatus(id:string,s:string){await api('/admin/orders/'+id+'/status',{method:'PATCH',body:JSON.stringify({status:s})});setOrders(x=>x.map(o=>o.id===id?{...o,status:s}:o))}
 return <><Header/><main className="container section"><div className="page-title"><div><span className="eyebrow">CONTROL CENTER</span><h1>Marketplace administration</h1></div><Link href="/dashboard" className="btn outline">Back to dashboard</Link></div>
 <div className="admin-tabs"><button className={tab==='ads'?'active':''} onClick={()=>setTab('ads')}>Pending adverts ({ads.length})</button><button className={tab==='reports'?'active':''} onClick={()=>setTab('reports')}>Reports ({reports.length})</button><button className={tab==='orders'?'active':''} onClick={()=>setTab('orders')}>Transactions ({orders.length})</button><button className={tab==='promotions'?'active':''} onClick={()=>setTab('promotions')}>Promotions ({promotions.length})</button><button className={tab==='verification'?'active':''} onClick={()=>setTab('verification')}>Verification ({verifications.length})</button></div>
 {tab==='ads'&&<div className="moderation-list">{ads.length?ads.map(a=><article className="moderation-card" key={a.id}><div className="moderation-images">{a.images?.length?a.images.map((i:any)=><img src={i.url} key={i.id}/>):<div className="no-image">No images</div>}</div><div className="moderation-info"><h2>{a.title}</h2><b>{money(a.price)} · {a.city}</b><p>{a.description}</p><div className="muted">Seller: {a.seller?.name} · {a.seller?.email}</div><div className="moderation-actions"><Link href={'/ad/'+a.id} className="btn outline">Preview</Link><button className="btn primary" onClick={()=>status(a.id,'ACTIVE')}>Approve</button><button className="btn danger" onClick={()=>status(a.id,'REJECTED')}>Reject</button></div></div></article>):<div className="empty"><h3>All clear</h3><p>No adverts are waiting for moderation.</p></div>}</div>}
 {tab==='reports'&&<div className="moderation-list">{reports.length?reports.map(r=><article className="panel report-row" key={r.id}><b>{r.reason}</b><span className="muted">Advert: {r.ad?.title}</span><span className="muted">Reported by: {r.reporter?.name} · {r.reporter?.email}</span>{r.details&&<p>{r.details}</p>}<div><Link href={'/ad/'+r.ad?.id} className="btn outline">View advert</Link><button className="btn primary" onClick={()=>resolve(r.id)}>Mark resolved</button></div></article>):<div className="empty"><h3>No open reports</h3></div>}</div>}
 {tab==='orders'&&<div className="orders-list">{orders.length?orders.map(o=><article className="order-card" key={o.id}><div className="order-main"><b>{o.ad?.title}</b><span>{money(o.total)} · Qty {o.quantity}</span><span className="muted">Buyer: {o.buyer?.name} · Seller: {o.seller?.name}</span><span className="muted">Payment: {o.paymentMethod} / {o.paymentStatus} · {o.deliveryMethod}</span></div><div className="order-actions"><strong>{o.status}</strong>{o.status!=='COMPLETED'&&o.status!=='CANCELLED'&&<><button className="btn outline" onClick={()=>orderStatus(o.id,'ACCEPTED')}>Accept</button><button className="btn outline" onClick={()=>orderStatus(o.id,'READY')}>Ready</button><button className="btn primary" onClick={()=>orderStatus(o.id,'COMPLETED')}>Complete</button></>}</div></article>):<div className="empty"><h3>No transactions</h3></div>}</div>}
 {tab==='promotions'&&<div className="orders-list">{promotions.length?promotions.map(p=><article className="order-card" key={p.id}><div className="order-main"><b>{p.type} · {p.ad?.title}</b><span>{money(p.amount)} · Ends {new Date(p.endsAt).toLocaleDateString()}</span><span className="muted">Seller: {p.seller?.name} · {p.seller?.email}</span></div><strong>{p.status}</strong></article>):<div className="empty"><h3>No promotions</h3></div>}</div>}
 {tab==='verification'&&<div className="orders-list">{verifications.length?verifications.map(v=><article className="order-card" key={v.id}><div className="order-main"><b>{v.name}</b><span>{v.email} · {v.phone||'No phone'} · {v.city||'No city'}</span><span className="muted">Status: {v.verificationStatus}</span></div><div className="order-actions"><button className="btn primary" onClick={async()=>{await api('/admin/users/'+v.id+'/verification',{method:'PATCH',body:JSON.stringify({status:'VERIFIED'})});setVerifications(x=>x.filter(i=>i.id!==v.id))}}>Verify</button><button className="btn outline" onClick={async()=>{const note=prompt('Reason for verification rejection (seller will see this):','Please provide the required verification information.');if(note===null)return;await api('/admin/users/'+v.id+'/verification',{method:'PATCH',body:JSON.stringify({status:'REJECTED',note:note.trim()||null})});setVerifications(x=>x.filter(i=>i.id!==v.id))}}>Reject</button></div></article>):<div className="empty"><h3>No verification requests</h3></div>}</div>}
 </main></>;
}
