'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import Header from '../components/Header';
import SellerTrial from '../components/SellerTrial';
import SellerSubscription from '../components/SellerSubscription';
import {api,money,mediaUrl} from '../lib';
import {ShieldCheck,Plus,MessageCircle,Heart,Package,LogOut,Pencil,CheckCircle,Megaphone,Eye,Star,ShoppingBag,ArrowRight,Search,BarChart3} from 'lucide-react';

export default function Dashboard(){
 const[u,setU]=useState<any>(null),[ads,setAds]=useState<any[]>([]),[metrics,setMetrics]=useState<any>(null),[loading,setLoading]=useState(true),[msg,setMsg]=useState('');
 async function load(){try{const [all,m]=await Promise.all([api('/ads/mine'),api('/users/me/metrics')]);setAds(Array.isArray(all)?all:[]);setMetrics(m)}catch(e:any){setMsg(e.message||'Could not load your marketplace centre.')}finally{setLoading(false)}}
 useEffect(()=>{const x=localStorage.getItem('minify_user');if(!x){location.href='/login?next=/dashboard';return}const z=JSON.parse(x);setU(z);if(z.role==='SELLER'||z.role==='ADMIN')load();else setLoading(false)},[]);
 function logout(){localStorage.removeItem('minify_token');localStorage.removeItem('minify_user');location.href='/';}
 async function markSold(id:string){if(!confirm('Mark this advert as sold?'))return;try{await api('/ads/'+id+'/sold',{method:'POST'});await load()}catch(e:any){setMsg(e.message||'Could not update advert.')}}
 async function renew(id:string){try{await api('/ads/'+id+'/renew',{method:'POST'});setMsg('Advert submitted for moderation again.');await load()}catch(e:any){setMsg(e.message||'Could not renew advert.')}}
 const seller=u?.role==='SELLER'||u?.role==='ADMIN';
 return <><Header/><main className="dashboard-shell">
  <section className="dashboard-hero"><div><span className="eyebrow">MY ACCOUNT · {seller?'SELLER CENTRE':'BUYER CENTRE'}</span><h1>Welcome back, {u?.name?.split(' ')[0]||'there'}.</h1><p>Everything you need to buy, sell and manage your MINIFY MARKET activity.</p><div className="dashboard-actions"><Link href="/" className="btn light-btn"><Search size={16}/> Browse marketplace</Link>{seller&&<Link href="/sell" className="btn primary"><Plus size={16}/> Post an advert</Link>}</div></div><div className="dashboard-hero-art"><BarChart3 size={42}/><b>{seller?metrics?.adverts??0:'Ready to shop'}</b><span>{seller?'active marketplace adverts':'saved activity & orders'}</span></div></section>
  <div className="dashboard-nav"><Link href="/dashboard" className="active">Overview</Link><Link href="/orders">Orders</Link><Link href="/favorites">Saved adverts</Link><Link href="/messages">Messages</Link><Link href="/notifications">Notifications</Link><Link href="/account">Account</Link><button onClick={logout}><LogOut size={15}/> Sign out</button></div>
  <div className="dashboard-grid"><section className="dashboard-main">
   {seller&&<><div className="dashboard-section-head"><div><span className="eyebrow">PERFORMANCE</span><h2>Your marketplace at a glance</h2></div><Link href="/seller-plans">Seller plans <ArrowRight size={15}/></Link></div><div className="metric-grid metric-grid-v2"><div className="metric-card"><Package/><b>{metrics?.adverts??0}</b><span>Adverts</span></div><div className="metric-card"><Eye/><b>{metrics?.views??0}</b><span>Total views</span></div><div className="metric-card"><Heart/><b>{metrics?.favorites??0}</b><span>Favorites</span></div><div className="metric-card"><MessageCircle/><b>{metrics?.conversations??0}</b><span>Messages</span></div><div className="metric-card"><ShoppingBag/><b>{metrics?.orders??0}</b><span>Orders</span></div><div className="metric-card"><CheckCircle/><b>{metrics?.completed??0}</b><span>Completed</span></div><div className="metric-card wide"><b>{money(metrics?.revenue??0)}</b><span>Completed order value</span></div></div></>}
   <div className="dashboard-section-head"><div><span className="eyebrow">QUICK ACCESS</span><h2>Manage your account</h2></div></div><div className="account-grid account-grid-v2"><Link href="/favorites" className="account-card"><Heart/><b>Saved adverts</b><span>Items you want to revisit.</span><ArrowRight/></Link><Link href="/saved-searches" className="account-card"><Star/><b>Saved searches</b><span>Return to your favourite searches.</span><ArrowRight/></Link><Link href="/messages" className="account-card"><MessageCircle/><b>Messages</b><span>Chat with buyers and sellers.</span><ArrowRight/></Link><Link href="/orders" className="account-card"><ShoppingBag/><b>My orders</b><span>Track requests and payments.</span><ArrowRight/></Link>{seller&&<Link href="/verification" className="account-card"><ShieldCheck/><b>Seller verification</b><span>Build more buyer confidence.</span><ArrowRight/></Link>}{seller&&<Link href="/sell" className="account-card accent"><Plus/><b>Post an advert</b><span>Put your next product on the market.</span><ArrowRight/></Link>}</div>
   {seller&&<><div className="dashboard-section-head listing-heading"><div><span className="eyebrow">INVENTORY</span><h2>Your adverts</h2></div><Link href="/sell">Post new <Plus size={15}/></Link></div>{msg&&<div className="notice">{msg}</div>}{loading?<div className="empty">Loading your adverts…</div>:ads.length?<div className="seller-ad-list">{ads.map(a=><article className="seller-ad" key={a.id}><Link className="seller-ad-main" href={'/ad/'+a.id}><div className="seller-thumb"><img src={mediaUrl(a.images?.[0]?.url||'/logo-market.png')} alt={a.title} loading="lazy"/><span className={'status status-'+String(a.status).toLowerCase()}>{String(a.status).replace('_',' ')}</span></div><div><div className="price">{money(a.price)}</div><b>{a.title}</b><div className="muted">{a.city} · {a.views||0} views · {new Date(a.createdAt).toLocaleDateString()}</div>{a.status==='REJECTED'&&a.moderationNote&&<div className="moderation-note"><strong>Rejected:</strong> {a.moderationNote}</div>}{a.status==='PENDING_REVIEW'&&<div className="moderation-note pending-note">Waiting for moderation.</div>}</div></Link><div className="seller-ad-actions">{a.status!=='SOLD'&&a.status!=='EXPIRED'&&<Link className="btn outline" href={'/sell/'+a.id}><Pencil size={15}/> Edit</Link>}{a.status==='ACTIVE'&&<Link className="btn outline" href={'/sell/'+a.id+'?promote=1'}><Megaphone size={15}/> Promote</Link>}{a.status==='EXPIRED'&&<button className="btn primary" onClick={()=>renew(a.id)}>Renew</button>}{a.status!=='SOLD'&&a.status!=='EXPIRED'&&<button className="btn outline" onClick={()=>markSold(a.id)}><CheckCircle size={15}/> Mark sold</button>}</div></article>)}</div>:<div className="empty"><Package size={34}/><h3>No adverts yet</h3><p>List your first item and start selling on MINIFY MARKET.</p><Link href="/sell" className="btn primary">Post your first advert</Link></div>}</>}
  </section><aside className="dashboard-side">{seller?<><div className="dashboard-side-card seller-status"><div className="side-icon"><CheckCircle/></div><span className="eyebrow">SELLER STATUS</span><h3>You're ready to sell</h3><p>Keep your listings accurate, fresh and easy to trust.</p><Link href="/seller-plans">View seller packages <ArrowRight size={15}/></Link></div><SellerTrial/><SellerSubscription/></>:<div className="dashboard-side-card buyer-status"><div className="side-icon"><ShoppingBag/></div><span className="eyebrow">SHOPPING MODE</span><h3>You're shopping as a buyer</h3><p>Browse adverts, save searches, chat with sellers and place orders when ready.</p><Link href="/">Explore marketplace <ArrowRight size={15}/></Link></div>}</aside></div>
 </main></>}
