'use client';
import { useEffect,useState } from 'react';
import Header from '../components/Header';
import SellerTrial from '../components/SellerTrial';
import SellerSubscription from '../components/SellerSubscription';
import { api,money,mediaUrl } from '../lib';
import { ShieldCheck,Plus,MessageCircle,Heart,Package,LogOut,Pencil,CheckCircle,Megaphone,Eye,Star,ShoppingBag } from 'lucide-react';
import Link from 'next/link';

export default function Dashboard(){
 const [u,setU]=useState<any>(null),[ads,setAds]=useState<any[]>([]),[metrics,setMetrics]=useState<any>(null),[loading,setLoading]=useState(true),[msg,setMsg]=useState('');
 async function load(){try{const [all,m]=await Promise.all([api('/ads/mine'),api('/users/me/metrics')]);setAds(Array.isArray(all)?all:[]);setMetrics(m)}catch(e:any){setMsg(e.message||'Could not load your seller center.')}finally{setLoading(false)}}
 useEffect(()=>{const x=localStorage.getItem('minify_user');if(!x){location.href='/login?next=/dashboard';return}const z=JSON.parse(x);setU(z);if(z.role==='SELLER'||z.role==='ADMIN')load();else setLoading(false)},[]);
 function logout(){localStorage.removeItem('minify_token');localStorage.removeItem('minify_user');location.href='/';}
 async function markSold(id:string){if(!confirm('Mark this advert as sold?'))return;try{await api('/ads/'+id+'/sold',{method:'POST'});await load()}catch(e:any){setMsg(e.message||'Could not update advert.')}}
 async function renew(id:string){try{await api('/ads/'+id+'/renew',{method:'POST'});setMsg('Advert submitted for moderation again.');await load()}catch(e:any){setMsg(e.message||'Could not renew advert.')}}
 const seller=u?.role==='SELLER'||u?.role==='ADMIN';
 return <><Header/><main className="container section">
  <div className="dash-welcome"><div><span className="eyebrow">MY ACCOUNT</span><h1>Welcome, {u?.name||'there'}</h1><p className="muted">Manage your marketplace activity from one place.</p></div><button className="logout" onClick={logout}><LogOut size={17}/> Sign out</button></div>
  <div className="account-grid"><Link href="/favorites" className="account-card"><Heart size={24}/><b>Favorites</b><span>Items you saved</span></Link><Link href="/saved-searches" className="account-card"><Star size={22}/><b>Saved searches</b><span>Get notified about matching adverts.</span></Link><Link href="/verification" className="account-card"><ShieldCheck size={22}/><b>Seller verification</b><span>Build buyer trust with a verified profile.</span></Link><Link href="/messages" className="account-card"><MessageCircle size={24}/><b>Messages</b><span>Chat with sellers and buyers</span></Link>{seller&&<Link href="/sell" className="account-card accent"><Plus size={24}/><b>Post an advert</b><span>Sell something today</span></Link>}{u?.role==='ADMIN'&&<Link href="/admin" className="account-card"><Package size={24}/><b>Admin moderation</b><span>Review submitted adverts</span></Link>}</div>
  {seller&&<><SellerTrial/><SellerSubscription/><section className="section"><div className="section-head"><div><span className="eyebrow">SELLER CENTER</span><h2>Performance overview</h2></div><Link href="/sell" className="btn primary"><Plus size={17}/> Post advert</Link></div>
   {msg&&<div className="notice">{msg}</div>}
   <div className="metric-grid"><div className="metric-card"><Package/><b>{metrics?.adverts??0}</b><span>Adverts</span></div><div className="metric-card"><Eye/><b>{metrics?.views??0}</b><span>Total views</span></div><div className="metric-card"><Heart/><b>{metrics?.favorites??0}</b><span>Favorites</span></div><div className="metric-card"><MessageCircle/><b>{metrics?.conversations??0}</b><span>Messages</span></div><div className="metric-card"><ShoppingBag/><b>{metrics?.orders??0}</b><span>Orders</span></div><div className="metric-card"><CheckCircle/><b>{metrics?.completed??0}</b><span>Completed</span></div><div className="metric-card wide"><b>{money(metrics?.revenue??0)}</b><span>Completed order value</span></div></div>
   <div className="section-head"><div><span className="eyebrow">LISTINGS</span><h2>Your adverts</h2></div></div>
   {loading?<div className="empty">Loading your adverts…</div>:ads.length?<div className="seller-ad-list">{ads.map(a=><article className="seller-ad" key={a.id}><Link className="seller-ad-main" href={'/ad/'+a.id}><div className="seller-thumb"><img src={mediaUrl(a.images?.[0]?.url||'/logo-market.png')} alt={a.title} loading="lazy"/><span className={'status status-'+String(a.status).toLowerCase()}>{String(a.status).replace('_',' ')}</span></div><div><div className="price">{money(a.price)}</div><b>{a.title}</b><div className="muted">{a.city} · {a.views||0} views · {new Date(a.createdAt).toLocaleDateString()}</div>{a.status==='REJECTED'&&a.moderationNote&&<div className="moderation-note"><strong>Why it was rejected:</strong> {a.moderationNote}</div>}{a.status==='PENDING_REVIEW'&&<div className="moderation-note pending-note">Your advert is waiting for moderation.</div>}</div></Link><div className="seller-ad-actions">{a.status!=='SOLD'&&a.status!=='EXPIRED'&&<Link className="btn outline" href={'/sell/'+a.id}><Pencil size={15}/> Edit</Link>}{a.status==='ACTIVE'&&<Link className="btn outline" href={'/sell/'+a.id+'?promote=1'}><Megaphone size={15}/> Promote</Link>}{a.status==='EXPIRED'&&<button className="btn primary" onClick={()=>renew(a.id)}>Renew advert</button>}{a.status!=='SOLD'&&a.status!=='EXPIRED'&&<button className="btn outline" onClick={()=>markSold(a.id)}><CheckCircle size={15}/> Mark sold</button>}</div></article>)}</div>:<div className="empty"><Package size={34}/><h3>No adverts yet</h3><p>List your first item and start selling on MINIFY MARKET.</p><Link href="/sell" className="btn primary">Post your first advert</Link></div>}
  </section></>}
  {!seller&&<div className="buyer-panel"><Package size={34}/><div><h2>You're shopping as a buyer</h2><p className="muted">Browse adverts, save searches, chat with sellers and place orders when ready.</p></div></div>}
 </main></>}
