'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import Header from '../components/Header';
import {api,money,mediaUrl} from '../lib';
import {ArrowRight,Heart,SlidersHorizontal,Search,MapPin,ShieldCheck,Grid3X3,List,ArrowUpDown} from 'lucide-react';

type Ad=any;
const fallbackCats=['Phones & Tablets','Vehicles','Property','Electronics','Home, Furniture & Appliances','Fashion','Beauty & Personal Care','Services','Jobs & Work','Babies & Kids','Food, Agriculture & Farming','Animals & Pets','Commercial Equipment & Tools','Leisure & Activities','Business & Industry'];
const conditions=['Any condition','New','Used','Refurbished'];
const cities=['All Uganda','Kampala','Wakiso','Mukono','Entebbe','Jinja','Mbarara'];

export default function AdsPage(){
 const [items,setItems]=useState<Ad[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''); const [categories,setCategories]=useState<any[]>([]);
 const [q,setQ]=useState(''),[category,setCategory]=useState('All categories'),[city,setCity]=useState('All Uganda');
 const [attributeKey,setAttributeKey]=useState(''),[attributeValue,setAttributeValue]=useState('');
 const [condition,setCondition]=useState('Any condition'),[min,setMin]=useState(''),[max,setMax]=useState('');
 const [sort,setSort]=useState('createdAt'),[view,setView]=useState<'grid'|'list'>('grid'),[page,setPage]=useState(1),[total,setTotal]=useState(0);
 const limit=24;
 const flatten=(xs:any[]):any[]=>xs.flatMap(c=>[c,...flatten(c.children||[])]);
 const allCategories=categories.length?flatten(categories):fallbackCats.map(name=>({name,children:[]}));
 const cats=['All categories',...allCategories.map(c=>c.name)];
 const findCategory=(xs:any[],name:string):any=>{for(const c of xs){if(c.name===name)return c;const hit=findCategory(c.children||[],name);if(hit)return hit}return null};
 const selectedCategory=category!=='All categories'?findCategory(categories,category):null;
 const filterOptions=(name:string)=>{const map:any={'Laptops & Computers':{key:'type',label:'Type',options:['Laptop','Desktop Computer','Server']},'Laptops':{key:'type',label:'Type',options:['Laptop']},'Desktop Computers':{key:'type',label:'Type',options:['Desktop Computer']},'Mobile Phones':{key:'brand',label:'Brand',options:['Apple','Samsung','Tecno','Infinix','Google','Xiaomi','Huawei','Nokia','OnePlus','Oppo','Vivo','Realme','Motorola','Sony','Itel','Nothing','Other']},'Cars':{key:'make',label:'Make',options:['Toyota','Subaru','Nissan','Mercedes-Benz','BMW','Honda','Hyundai','Isuzu','Mitsubishi','Audi','Ford','Kia','Land Rover','Lexus','Other']},'TV & Video':{key:'type',label:'Type',options:['Smart TV','LED TV','OLED TV','QLED TV','Projector','TV Accessories']},'Tablets':{key:'brand',label:'Brand',options:['Apple','Samsung','Lenovo','Huawei','Xiaomi','Other']},'Smart Watches':{key:'brand',label:'Brand',options:['Apple','Samsung','Huawei','Xiaomi','Amazfit','Garmin','Other']},'Furniture':{key:'type',label:'Type',options:['Sofa','Bed','Dining Set','Wardrobe','Office Furniture','Other']},'Dogs':{key:'breed',label:'Breed',options:['German Shepherd','Rottweiler','Labrador','Pitbull','Husky','Maltese','Boerboel','Golden Retriever','Other']},'Cats & Kittens':{key:'breed',label:'Breed',options:['Persian','British Shorthair','Siamese','Maine Coon','Other']},'Birds':{key:'species',label:'Bird type',options:['Parrot','Canary','Pigeon','Other']},'Fish':{key:'waterType',label:'Water type',options:['Freshwater','Saltwater','Both']},'Pet Supplies':{key:'type',label:'Type',options:['Food','Cages & Kennels','Aquariums','Grooming','Toys','Accessories','Vitamins','Other']},'Houses & Apartments For Rent':{key:'propertyType',label:'Property type',options:['House','Apartment','Flat','Room','Studio','Other']},'Houses & Apartments For Sale':{key:'propertyType',label:'Property type',options:['House','Apartment','Flat','Other']},'Land & Plots For Sale':{key:'landType',label:'Land type',options:['Residential','Commercial','Agricultural','Mixed Use','Other']},'Jobs':{key:'jobType',label:'Job type',options:['Full-time','Part-time','Contract','Temporary','Internship','Volunteer']},'Seeking Work / CVs':{key:'experience',label:'Experience',options:['No experience','Less than 1 year','1-2 years','3-5 years','6-10 years','10+ years']},'Motorcycles & Scooters':{key:'make',label:'Make',options:['Honda','Yamaha','Suzuki','Bajaj','TVS','Kawasaki','Other']}};return map[name]||null};
 const af=filterOptions(category);
 useEffect(()=>{const p=new URLSearchParams(location.search);setQ(p.get('q')||'');setCategory(p.get('category')||'All categories');api('/categories').then((x:any[])=>setCategories(Array.isArray(x)?x:[])).catch(()=>{});},[]);
 useEffect(()=>{load();},[q,category,city,condition,min,max,sort,page]);
 async function load(){setLoading(true);setError('');try{const p=new URLSearchParams({limit:String(limit),page:String(page),sort,order:sort==='price'?'asc':'desc'});if(q)p.set('q',q);if(category!=='All categories')p.set('category',category);
   if(attributeKey&&attributeValue){p.set('attributeKey',attributeKey);p.set('attributeValue',attributeValue)}if(city!=='All Uganda')p.set('city',city);if(condition!=='Any condition')p.set('condition',condition.toUpperCase());if(min)p.set('minPrice',min);if(max)p.set('maxPrice',max);const d=await api('/ads?'+p.toString());setItems(Array.isArray(d)?d:(d.items||[]));setTotal(Number(d.total||d.count||0));}catch(e:any){setError(e.message||'Could not load adverts.');}finally{setLoading(false);}}
 function reset(){setQ('');setCategory('All categories');setCity('All Uganda');setCondition('Any condition');setMin('');setMax('');setAttributeKey('');setAttributeValue('');setPage(1);}
 return <><Header/><main className="container marketplace-browse">
  <div className="browse-head"><div><span className="eyebrow">MINIFY MARKET</span><h1>Find it. Compare it. Buy it.</h1><p className="muted">Discover products from sellers across Uganda.</p></div><div className="view-toggle"><button className={view==='grid'?'active':''} onClick={()=>setView('grid')} aria-label="Grid view"><Grid3X3 size={18}/></button><button className={view==='list'?'active':''} onClick={()=>setView('list')} aria-label="List view"><List size={18}/></button></div></div>
  <form className="browse-search" onSubmit={e=>{e.preventDefault();setPage(1);load()}}><Search size={19}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search phones, laptops, TVs, accessories..."/><button className="btn primary">Search</button></form><div className="browse-trust"><div><ShieldCheck size={17}/><span><b>Shop with confidence</b><small>Check seller profiles, reviews and item details before paying.</small></span></div><div><MapPin size={17}/><span><b>Uganda-wide</b><small>Browse Kampala and sellers across the country.</small></span></div><div><Heart size={17}/><span><b>Save what you like</b><small>Keep adverts and searches for later.</small></span></div></div><div className="browse-shortcuts"><span>Popular:</span><button type="button" onClick={()=>{setCategory("Mobile Phones");setPage(1)}}>Mobile phones</button><button type="button" onClick={()=>{setCategory("Laptops & Computers");setPage(1)}}>Laptops</button><button type="button" onClick={()=>{setCategory("TV & Video");setPage(1)}}>TVs</button><button type="button" onClick={()=>{setCondition("New");setPage(1)}}>Brand new</button><button type="button" onClick={()=>{setCity("Kampala");setPage(1)}}>Kampala</button></div>
  {selectedCategory&&selectedCategory.children?.length>0&&<section className="category-landing"><div className="category-landing-head"><div><span className="eyebrow">{selectedCategory.name.toUpperCase()}</span><h2>Browse {selectedCategory.name}</h2><p>Choose a subcategory to narrow the adverts, or keep browsing everything in this department.</p></div></div><div className="subcategory-grid">{selectedCategory.children.map((c:any)=><Link key={c.id} href={'/ads?category='+encodeURIComponent(c.name)} className="subcategory-card"><b>{c.name}</b><span>{c.children?.length?`${c.children.length} more types`:'View adverts'} <ArrowRight size={14}/></span></Link>)}</div></section>}
  <div className="browse-layout"><aside className="filter-panel"><div className="filter-title"><b>Filters</b><button onClick={reset} type="button">Reset</button></div>
   <label>Category<select value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}>{cats.map(x=><option key={x}>{x}</option>)}</select></label>
   <label>Location<select value={city} onChange={e=>{setCity(e.target.value);setPage(1)}}>{cities.map(x=><option key={x}>{x}</option>)}</select></label>
   {af&&<label>{af.label}<select value={attributeValue} onChange={e=>{setAttributeKey(af.key);setAttributeValue(e.target.value);setPage(1)}}><option value="">All {af.label.toLowerCase()}s</option>{af.options.map((x:string)=><option key={x}>{x}</option>)}</select></label>}
   <label>Condition<select value={condition} onChange={e=>{setCondition(e.target.value);setPage(1)}}>{conditions.map(x=><option key={x}>{x}</option>)}</select></label>
   <div className="price-fields"><label>Min price<input inputMode="numeric" value={min} onChange={e=>setMin(e.target.value)} placeholder="UGX"/></label><label>Max price<input inputMode="numeric" value={max} onChange={e=>setMax(e.target.value)} placeholder="UGX"/></label></div>
   <button className="btn primary full" type="button" onClick={()=>{setPage(1);load()}}><SlidersHorizontal size={17}/> Apply filters</button>
  </aside>
  <section className="results"><div className="results-bar"><div><b>{loading?'Finding productsÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¦':total?`${total.toLocaleString()} adverts`:`${items.length} adverts`}</b>{q&&<span className="muted"> for ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ{q}ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â</span>}</div><label className="sort"><ArrowUpDown size={16}/><select value={sort} onChange={e=>{setSort(e.target.value);setPage(1)}}><option value="createdAt">Newest</option><option value="price">Lowest price</option><option value="views">Most viewed</option></select></label></div>
   {error&&<div className="notice">{error}</div>}
   {loading?<div className="grid">{Array.from({length:8}).map((_,i)=><div className="listing skeleton-card" key={i}/>)}</div>:items.length?<div className={view==='grid'?'grid':'listing-results'}>{items.map(a=><AdCard key={a.id} ad={a} list={view==='list'}/>)}</div>:<div className="empty browse-empty"><Search size={30}/><h3>No adverts found</h3><p>Try a different search or remove some filters.</p><button className="btn outline" onClick={reset}>Clear filters</button></div>}
   {!loading&&items.length>=limit&&<div className="pagination"><button className="btn outline" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page}</span><button className="btn outline" onClick={()=>setPage(p=>p+1)}>Next</button></div>}
  </section></div></main></>;
}

function AdCard({ad,list}:{ad:Ad;list:boolean}){const [saved,setSaved]=useState(false),[busy,setBusy]=useState(false);const image=mediaUrl(ad.images?.[0]?.url||ad.imageUrl||'');useEffect(()=>{const raw=localStorage.getItem('minify_user');if(!raw)return;const u=JSON.parse(raw);api('/favorites/'+u.id).then((x:any[])=>setSaved(Array.isArray(x)&&x.some(f=>f.adId===ad.id))).catch(()=>{})},[ad.id]);async function toggle(e:React.MouseEvent){e.preventDefault();e.stopPropagation();const raw=localStorage.getItem('minify_user');if(!raw){location.href='/login?next='+encodeURIComponent('/ad/'+ad.id);return}const u=JSON.parse(raw);setBusy(true);try{if(saved)await api('/favorites/'+u.id+'/'+ad.id,{method:'DELETE'});else await api('/favorites',{method:'POST',body:JSON.stringify({userId:u.id,adId:ad.id})});setSaved(!saved)}catch{}finally{setBusy(false)}}return <Link className={`market-card ${list?'market-card-list':''}`} href={`/ad/${ad.id}`}>
 <div className="market-card-media">{image?<img src={image} alt={ad.title||'Product'} loading="lazy"/>:<div className="image-placeholder">MINIFY<br/>MARKET</div>}{ad.featuredUntil||ad.boostUntil?<span className="featured-badge">Featured</span>:null}<button type="button" className={`save-card ${saved?'saved':''}`} aria-label="Save advert" onClick={toggle} disabled={busy}><Heart size={18} fill={saved?'currentColor':'none'}/></button></div>
 <div className="market-card-body"><div className="price">{money(ad.price)}</div><h3>{ad.title}</h3><div className="card-meta"><span><MapPin size={14}/>{ad.city||'Uganda'}</span><span>{ad.condition||'Used'}</span></div><div className="seller-line">{ad.seller?.verified&&<ShieldCheck size={14}/>} {ad.seller?.name||'MINIFY seller'}{ad.negotiable&&<b>Negotiable</b>}</div></div></Link>}
