'use client';
import {useEffect,useState} from 'react';
export type Language='en'|'sw'|'lg';
export const languages=[{code:'en' as const,label:'English',native:'English'},{code:'sw' as const,label:'Swahili',native:'Kiswahili'},{code:'lg' as const,label:'Luganda',native:'Luganda'}];
const en:Record<string,string>={home:'Home',saved:'Saved',sell:'Sell',messages:'Messages',profile:'Profile',search:'Search',signIn:'Sign in',account:'Account',searchPlaceholder:'Search phones, laptops, TVs & more',browse:'Browse marketplace',categories:'Categories',jobs:'Jobs & CVs',help:'Help & support',language:'Language',discover:'DISCOVER',browseDepartments:'Browse departments',browseSub:'Choose a main category, then narrow down to exactly what you want.',moreCategories:'More categories',recommended:'RECOMMENDED FOR YOU',fresh:'Fresh finds',freshSub:'The newest adverts from sellers across MINIFY MARKET',viewMarketplace:'View marketplace',sellOn:'SELL ON MINIFY',sellerTitle:'Your product deserves the right buyer.',sellerBody:'Post an advert in minutes, connect with interested buyers and manage your sales from one account.'};
const sw:Record<string,string>={home:'Nyumbani',saved:'Zilizohifadhiwa',sell:'Uza',messages:'Ujumbe',profile:'Wasifu',search:'Tafuta',signIn:'Ingia',account:'Akaunti',searchPlaceholder:'Tafuta simu, laptop, TV na zaidi',browse:'Vinjari soko',categories:'Aina',jobs:'Kazi na CV',help:'Msaada',language:'Lugha',discover:'GUNDUA',browseDepartments:'Vinjari idara',browseSub:'Chagua aina kuu kisha tafuta unachohitaji.',moreCategories:'Aina zaidi',recommended:'UNAPENDEKEZEWA',fresh:'Matangazo mapya',freshSub:'Matangazo mapya kutoka kwa wauzaji wa MINIFY MARKET',viewMarketplace:'Tazama soko',sellOn:'UZA KWENYE MINIFY',sellerTitle:'Bidhaa yako inastahili mnunuzi sahihi.',sellerBody:'Weka tangazo kwa dakika, wasiliana na wanunuzi na simamia mauzo yako kutoka akaunti moja.'};
const lg:Record<string,string>={home:'Awaka',saved:'Ebiterekeddwa',sell:'Tunda',messages:'Obubaka',profile:'Profayiro',search:'Noonya',signIn:'Yingira',account:'Akaawunti',searchPlaceholder:'Noonya essimu, laptop, TV n’ebirala',browse:'Kebera akatale',categories:'Ebika',jobs:'Emirimu ne CV',help:'Obuyambi',language:'Olulimi',discover:'KEBERA',browseDepartments:'Kebera ebitundu',browseSub:'Londa ekika ekikulu oluvannyuma onoonye ky’oyagala.',moreCategories:'Ebika ebirala',recommended:'BIKUSUUBIRWA',fresh:'Ebirango ebipya',freshSub:'Ebirango ebipya okuva ku batunzi ba MINIFY MARKET',viewMarketplace:'Laba akatale',sellOn:'TUNDA KU MINIFY',sellerTitle:'Ekintu kyo kisaanira omuguzi omutuufu.',sellerBody:'Teka ekirango mu ddakiika, yunga ku baguzi era ddukanya okutunda kwo okuva mu akawunti emu.'};
const all={en,sw,lg};
export function useLanguage(){const [language,setLanguage]=useState<Language>('en');useEffect(()=>{const load=()=>{const v=localStorage.getItem('minify_language');if(v==='sw'||v==='lg'||v==='en')setLanguage(v)};load();const on=(e:Event)=>{const v=(e as CustomEvent<Language>).detail;if(v)setLanguage(v)};window.addEventListener('minify-language',on);return()=>window.removeEventListener('minify-language',on)},[]);const change=(v:Language)=>{localStorage.setItem('minify_language',v);setLanguage(v);window.dispatchEvent(new CustomEvent('minify-language',{detail:v}))};return{language,setLanguage:change,t:(key:string)=>all[language][key]||en[key]||key};}
