'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import Header from './components/Header';
import {useLanguage} from './i18n';
import {api,money} from './lib';

import {ArrowRight,CheckCircle2,ChevronRight,Heart,MapPin,Search,ShieldCheck,TrendingUp,Zap} from 'lucide-react';
const categoryImage=(name:string)=>{const n=name.toLowerCase();if(n.includes('phone')||n.includes('tablet'))return 'phones.png';if(n.includes('vehicle'))return 'vehicles.png';if(n.includes('property'))return 'property.png';if(n.includes('electronic'))return 'electronics.png';if(n.includes('home')||n.includes('furniture')||n.includes('appliance'))return 'home.png';if(n.includes('beauty'))return 'beauty.png';if(n.includes('fashion'))return 'fashion.png';if(n.includes('leisure'))return 'leisure.png';if(n.includes('job')||n.includes('work'))return n.includes('cv')?'cvs.png':'jobs.png';if(n.includes('baby'))return 'babies.png';if(n.includes('pet')||n.includes('animal'))return 'animals.png';if(n.includes('food')||n.includes('agriculture'))return 'food.png';if(n.includes('commercial'))return 'commercial.png';if(n.includes('service'))return 'services.png';return 'electronics.png';};
const perks=[['Verified sellers','Trade with confidence','Every seller profile shows verification status.'],['Secure conversations','Keep deals on-platform','Chat before you decide and keep the details clear.'],['Local discovery','Find deals near you','Discover products from Kampala and across Uganda.']];
export default function Home(){
 const {t}=useLanguage();
 const [ads,setAds]=useState<any[]>([]),[categories,setCategories]=useState<any[]>([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{api('/categories').then((x:any)=>setCategories(Array.isArray(x)?x:[])).catch(()=>setCategories([]));api('/ads?limit=16&sort=createdAt&order=desc').then(d=>setAds(Array.isArray(d)?d:(d?.items||[]))).catch(()=>setAds([])).finally(()=>setLoading(false))},[]);
 const go=(value:string)=>{const v=value.trim();location.href=v?'/ads?'+new URLSearchParams({q:v}).toString():'/ads'};
 const search=(e:any)=>{e.preventDefault();go(q)};
 const cards=(items:any[])=><div className="product-grid">{items.map((a:any)=><Link href={'/ad/'+a.id} className="product" key={a.id}><div className="product-img">{a.images?.[0]?.url?<img src={a.images[0].url} alt={a.title}/>:<div className="product-placeholder"><span>MINIFY</span><small>No photo yet</small></div>}<span className="image-watermark">POSTED ON MINIFY MARKET · {a.seller?.name||'SELLER'}</span>{a.condition==='NEW'&&<span className="badge">NEW</span>}{(a.featuredUntil||a.boostUntil)&&<span className="featured"><Zap size={11}/> Featured</span>}<span className="heart" aria-label="Save advert"><Heart size={19}/></span></div><div className="product-body"><div className="product-top"><span className="location"><MapPin size={12}/>{a.city||'Uganda'}</span>{a.negotiable&&<span className="negotiable">Negotiable</span>}</div><h3>{a.title}</h3><strong>{money(a.price)}</strong><div className="product-foot"><span>{a.condition==='NEW'?'Brand new':a.condition==='REFURBISHED'?'Refurbished':'Used'}</span><span>{a.seller?.verified?'Verified seller':'Seller'}</span></div></div></Link>)}</div>;
 return <><Header/><main className="home">
 <section className="hero"><div className="hero-inner"><div className="hero-copy"><div className="eyebrow">UGANDA'S SMARTER MARKETPLACE</div><h1>Everything you want.<br/><em>Closer to you.</em></h1><p>Buy and sell phones, laptops, TVs, fashion, accessories and more from people and businesses across Uganda.</p><form className="hero-search" onSubmit={search}><span className="hero-search-icon" aria-hidden="true"><Search size={20}/></span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search for phones, laptops, TVs, fashion & more"/><button>Search</button></form><div className="hero-trust"><span><CheckCircle2 size={15}/> Verified sellers</span><span><ShieldCheck size={15}/> Safer deals</span><span><MapPin size={15}/> Across Uganda</span></div></div><div className="hero-showcase"><div className="showcase-main"><span>MINIFY MARKET</span><b>Good products.<br/>Better deals.</b><small>Discover something worth buying today.</small><div className="showcase-pills"><i>Fresh listings</i><i>Local sellers</i></div></div><div className="showcase-mini"><TrendingUp size={18}/><div><b>Trending now</b><span>Phones & electronics</span></div></div></div></div></section>
 <section className="quick-nav"><div className="container quick-inner"><span>Popular searches</span>{['iPhone','Samsung','Laptops','TVs','AirPods','PlayStation'].map(x=><button key={x} onClick={()=>go(x)}>{x}<ChevronRight size={13}/></button>)}</div></section>
 <section className="container section"><div className="section-head"><div><span className="eyebrow">{t('discover')}</span><h2>{t('browseDepartments')}</h2><p>{t('browseSub')}</p></div><Link href="/categories" className="see-all">{t('moreCategories')} <ArrowRight size={15}/></Link></div><div className="category-grid">{categories.slice(0,15).map((c:any)=>{return <Link href={'/ads?category='+encodeURIComponent(c.name)} className="category" key={c.id}><span className="cat-icon"><img src={'/categories/'+categoryImage(c.name)} alt=""/></span><div><b>{c.name}</b><small>{c.children?.length||0} subcategories</small></div><ChevronRight size={16}/></Link>})}</div><div className="home-category-strip">{categories.slice(0,8).map((c:any)=><div className="home-dept" key={c.id}><Link href={'/ads?category='+encodeURIComponent(c.name)}><b>{c.name}</b><span>Explore {c.children?.length||0} categories <ArrowRight size={13}/></span></Link>{(c.children||[]).slice(0,5).map((child:any)=><Link key={child.id} href={'/ads?category='+encodeURIComponent(child.name)}>{child.name}</Link>)}</div>)}</div></section>
 <section className="confidence"><div className="container"><div className="section-head light"><div><span className="eyebrow">WHY MINIFY</span><h2>Built for better local deals</h2></div></div><div className="perk-grid">{perks.map(([title,sub,body],i)=><div className="perk" key={title}><div className="perk-number">0{i+1}</div><div><b>{title}</b><strong>{sub}</strong><p>{body}</p></div></div>)}</div></div></section>
 <section className="container section listings"><div className="section-head"><div><span className="eyebrow">{t('recommended')}</span><h2>{t('fresh')}</h2><p>{t('freshSub')}</p></div><Link href="/ads" className="see-all">{t('viewMarketplace')} <ArrowRight size={15}/></Link></div>{loading?<div className="loading-grid">{Array.from({length:8}).map((_,i)=><div className="skeleton" key={i}/>)}</div>:ads.length?cards(ads):<div className="empty-state"><h3>The marketplace is getting ready</h3><p>Be among the first sellers to list something great.</p><Link href="/sell" className="btn primary">Post an advert</Link></div>}</section>
 {ads.length>4&&<section className="container section deal-section"><div className="deal-banner"><div><span className="eyebrow">DEALS WORTH A LOOK</span><h2>Find more. Compare better.</h2><p>Browse the full marketplace and discover products across Uganda.</p></div><Link href="/ads" className="btn light-btn">Explore all listings <ArrowRight size={16}/></Link></div></section>}
 <section className="container section seller-cta"><div className="seller-copy"><span className="eyebrow">{t('sellOn')}</span><h2>{t('sellerTitle')}</h2><p>{t('sellerBody')}</p><div className="seller-points"><span><CheckCircle2 size={15}/> Easy listing</span><span><CheckCircle2 size={15}/> Seller profile</span><span><CheckCircle2 size={15}/> Direct chat</span></div></div><Link href="/sell" className="btn primary">Start selling <ArrowRight size={16}/></Link></section>
 </main></>;
}