'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import Header from './components/Header';
import {api,money} from './lib';
import {ArrowRight,CheckCircle2,ChevronRight,MapPin,ShieldCheck,Star,TrendingUp,Zap} from 'lucide-react';
const cats=[['Phones & Tablets','📱'],['Laptops & Computers','💻'],['TV & Video','📺'],['Audio','🎧'],['Wearables','⌚'],['Gaming','🎮'],['Home & Living','🏠'],['Vehicles','🚗']];
const perks=[['Verified sellers','Trade with confidence','Every seller profile shows verification status.'],['Secure conversations','Keep deals on-platform','Chat before you decide and keep the details clear.'],['Local discovery','Find deals near you','Discover products from Kampala and across Uganda.']];
export default function Home(){
 const [ads,setAds]=useState<any[]>([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{api('/ads?limit=16&sort=createdAt&order=desc').then(d=>setAds(Array.isArray(d)?d:(d?.items||[]))).catch(()=>setAds([])).finally(()=>setLoading(false))},[]);
 const go=(value:string)=>{const v=value.trim();location.href=v?'/ads?'+new URLSearchParams({q:v}).toString():'/ads'};
 const search=(e:any)=>{e.preventDefault();go(q)};
 const cards=(items:any[])=><div className="product-grid">{items.map((a:any)=><Link href={'/ad/'+a.id} className="product" key={a.id}><div className="product-img">{a.images?.[0]?.url?<img src={a.images[0].url} alt={a.title}/>:<div className="product-placeholder"><span>MINIFY</span><small>No photo yet</small></div>}{a.condition==='NEW'&&<span className="badge">NEW</span>}{(a.featuredUntil||a.boostUntil)&&<span className="featured"><Zap size={11}/> Featured</span>}<span className="heart">♡</span></div><div className="product-body"><div className="product-top"><span className="location"><MapPin size={12}/>{a.city||'Uganda'}</span>{a.negotiable&&<span className="negotiable">Negotiable</span>}</div><h3>{a.title}</h3><strong>{money(a.price)}</strong><div className="product-foot"><span>{a.condition==='NEW'?'Brand new':a.condition==='REFURBISHED'?'Refurbished':'Used'}</span><span>{a.seller?.verified?'Verified seller':'Seller'}</span></div></div></Link>)}</div>;
 return <><Header/><main className="home">
 <section className="hero"><div className="hero-inner"><div className="hero-copy"><div className="eyebrow">UGANDA'S SMARTER MARKETPLACE</div><h1>Everything you want.<br/><em>Closer to you.</em></h1><p>Buy and sell phones, laptops, TVs, fashion, accessories and more from people and businesses across Uganda.</p><form className="hero-search" onSubmit={search}><span className="hero-search-icon">⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search for phones, laptops, TVs, fashion & more"/><button>Search</button></form><div className="hero-trust"><span><CheckCircle2 size={15}/> Verified sellers</span><span><ShieldCheck size={15}/> Safer deals</span><span><MapPin size={15}/> Across Uganda</span></div></div><div className="hero-showcase"><div className="showcase-main"><span>MINIFY MARKET</span><b>Good products.<br/>Better deals.</b><small>Discover something worth buying today.</small><div className="showcase-pills"><i>Fresh listings</i><i>Local sellers</i></div></div><div className="showcase-mini"><TrendingUp size={18}/><div><b>Trending now</b><span>Phones & electronics</span></div></div></div></div></section>
 <section className="quick-nav"><div className="container quick-inner"><span>Popular searches</span>{['iPhone','Samsung','Laptops','TVs','AirPods','PlayStation'].map(x=><button key={x} onClick={()=>go(x)}>{x}<ChevronRight size={13}/></button>)}</div></section>
 <section className="container section"><div className="section-head"><div><span className="eyebrow">BROWSE</span><h2>Shop by category</h2><p>Start with what you need</p></div><Link href="/ads" className="see-all">All categories <ArrowRight size={15}/></Link></div><div className="category-grid">{cats.map(([name,icon])=><Link href={'/ads?category='+encodeURIComponent(name)} className="category" key={name}><span className="cat-icon">{icon}</span><div><b>{name}</b><small>Explore listings</small></div><ChevronRight size={16}/></Link>)}</div></section>
 <section className="confidence"><div className="container"><div className="section-head light"><div><span className="eyebrow">WHY MINIFY</span><h2>Built for better local deals</h2></div></div><div className="perk-grid">{perks.map(([title,sub,body],i)=><div className="perk" key={title}><div className="perk-number">0{i+1}</div><div><b>{title}</b><strong>{sub}</strong><p>{body}</p></div></div>)}</div></div></section>
 <section className="container section listings"><div className="section-head"><div><span className="eyebrow">JUST IN</span><h2>Fresh finds</h2><p>The newest adverts from sellers</p></div><Link href="/ads" className="see-all">View marketplace <ArrowRight size={15}/></Link></div>{loading?<div className="loading-grid">{Array.from({length:8}).map((_,i)=><div className="skeleton" key={i}/>)}</div>:ads.length?cards(ads):<div className="empty-state"><h3>The marketplace is getting ready</h3><p>Be among the first sellers to list something great.</p><Link href="/sell" className="btn primary">Post an advert</Link></div>}</section>
 {ads.length>4&&<section className="container section deal-section"><div className="deal-banner"><div><span className="eyebrow">DEALS WORTH A LOOK</span><h2>Find more. Compare better.</h2><p>Browse the full marketplace and discover products across Uganda.</p></div><Link href="/ads" className="btn light-btn">Explore all listings <ArrowRight size={16}/></Link></div></section>}
 <section className="container section seller-cta"><div className="seller-copy"><span className="eyebrow">SELL ON MINIFY</span><h2>Your product deserves<br/>the right buyer.</h2><p>Post an advert in minutes, connect with interested buyers and manage your sales from one account.</p><div className="seller-points"><span><CheckCircle2 size={15}/> Easy listing</span><span><CheckCircle2 size={15}/> Seller profile</span><span><CheckCircle2 size={15}/> Direct chat</span></div></div><Link href="/sell" className="btn primary">Start selling <ArrowRight size={16}/></Link></section>
 </main></>;
}