import Link from 'next/link';
import { Search, ShieldCheck, Truck, MessageCircle, SlidersHorizontal } from 'lucide-react';
import Header from './components/Header';
import { api, money } from './lib';

async function getAds(p:any){
 try{const q=new URLSearchParams();for(const k of ['q','categoryId','condition','city','minPrice','maxPrice','sort','order','page'])if(p[k])q.set(k,String(p[k]));q.set('limit','24');const d=await api('/ads?'+q.toString());return d?.items?d:{items:Array.isArray(d)?d:[],total:Array.isArray(d)?d.length:0,page:1,pages:1};}catch{return {items:[],total:0,page:1,pages:1};}
}
export default async function Home({searchParams}:{searchParams:Promise<any>}){
 const p=await searchParams;const data=await getAds(p);let cats:any[]=[];try{cats=await api('/categories')}catch{}
 const page=Number(data.page)||1,pages=Number(data.pages)||1;
 return <><Header/><main>
 <section className="hero"><div className="container hero-inner"><div><span className="eyebrow">UGANDA'S GADGET MARKETPLACE</span><h1>Find the gadget<br/>you've been looking for.</h1><p>Buy and sell phones, laptops, TVs, accessories and more from people and businesses across Uganda.</p><div className="hero-actions"><Link href="/sell" className="btn primary">Sell an item</Link><a href="#listings" className="btn outline">Browse adverts</a></div></div></div></section>
 <section className="trust"><div className="container trust-grid"><div><ShieldCheck size={22}/><b>Shop with confidence</b><span>Clear listings & seller details</span></div><div><MessageCircle size={22}/><b>Chat with sellers</b><span>Ask before you buy</span></div><div><Truck size={22}/><b>Meet or arrange delivery</b><span>Choose what works for you</span></div></div></section>
 <section className="container cats section"><div className="section-head"><div><span className="eyebrow">EXPLORE</span><h2>Browse categories</h2></div></div><div className="grid category-grid">{cats.map(c=><Link className="cat" href={'/?categoryId='+c.id} key={c.id}><span>{c.name}</span><small>View adverts →</small></Link>)}</div></section>
 <section id="listings" className="container section"><div className="section-head"><div><span className="eyebrow">MARKETPLACE</span><h2>{p.q?`Results for “${p.q}”`:'Latest adverts'}</h2><span className="muted">{data.total||0} adverts available</span></div><Link href="/sell" className="btn primary">Post an advert</Link></div>
 <form className="filter-bar" action="/" method="get"><div className="filter-search"><Search size={17}/><input name="q" defaultValue={p.q||''} placeholder="Search phones, laptops, TVs..."/></div><select name="condition" defaultValue={p.condition||''}><option value="">Any condition</option><option>NEW</option><option>LIKE_NEW</option><option>USED</option><option>REFURBISHED</option></select><input name="city" defaultValue={p.city||''} placeholder="City"/><input name="minPrice" defaultValue={p.minPrice||''} placeholder="Min UGX" type="number"/><input name="maxPrice" defaultValue={p.maxPrice||''} placeholder="Max UGX" type="number"/><select name="sort" defaultValue={p.sort||'createdAt'}><option value="createdAt">Newest</option><option value="price">Price</option><option value="views">Popular</option></select><button className="btn primary" type="submit"><SlidersHorizontal size={16}/>Filter</button></form>
 {data.items.length?<><div className="grid">{data.items.map((a:any)=><Link className="listing" href={'/ad/'+a.id} key={a.id}><div className="listing-image"><img src={a.images?.[0]?.url||'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?auto=format&fit=crop&w=900&q=80'}/>{a.condition&&<span className="condition">{String(a.condition).replace('_',' ')}</span>}</div><div className="listing-body"><div className="price">{money(a.price)}</div><b className="listing-title">{a.title}</b><div className="muted">{a.city||'Uganda'} · {a.seller?.name||'Seller'}</div></div></Link>)}</div>
 <div className="pagination">{page>1&&<Link className="btn outline" href={'/?'+new URLSearchParams({...p,page:String(page-1)} as any).toString()}>← Previous</Link>}<span>Page {page} of {pages}</span>{page<pages&&<Link className="btn outline" href={'/?'+new URLSearchParams({...p,page:String(page+1)} as any).toString()}>Next →</Link>}</div></>:<div className="empty"><Search size={32}/><h3>No adverts found</h3><p>Try another search or adjust your filters.</p><Link href="/" className="btn outline">Clear filters</Link></div>}
 </section></main><footer className="footer"><div className="container footer-inner"><div><b>MINIFY MARKET</b><p>Uganda's marketplace for gadgets.</p></div><span>© {new Date().getFullYear()} MINIFY MARKET · MINIFY GADGETS</span></div></footer></>;
}
