import {useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,FlatList,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {useLocalSearchParams} from 'expo-router';
import AdCard from '@/components/AdCard';
import {api,type Ad} from '@/lib/api';
import {fallbackFields,type Field} from '@/lib/category-fields';
const GREEN='#0B8F55';
type Category={id:string;name:string;parentId:string|null;children?:Category[]};
const cities=['All Uganda','Kampala','Wakiso','Mukono','Entebbe','Jinja','Mbarara'];
const conditions=['Any','NEW','USED','REFURBISHED'];
export default function SearchScreen(){
 const params=useLocalSearchParams<{q?:string;category?:string}>();
 const[q,setQ]=useState(String(params.q||'')),[ads,setAds]=useState<Ad[]>([]),[loading,setLoading]=useState(false),[refresh,setRefresh]=useState(false);
 const[city,setCity]=useState('All Uganda'),[condition,setCondition]=useState('Any'),[min,setMin]=useState(''),[max,setMax]=useState(''),[sort,setSort]=useState('createdAt');
 const[categories,setCategories]=useState<Category[]>([]),[category,setCategory]=useState(String(params.category||'')),[attributeFilters,setAttributeFilters]=useState<Record<string,string>>({});
 const flatten=(xs:Category[]):Category[]=>xs.flatMap(x=>[x,...flatten(x.children||[])]);
 const all=useMemo(()=>flatten(categories),[categories]); const selected=all.find(x=>x.name===category);
 const rootName=useMemo(()=>{if(!selected)return '';const walk=(xs:Category[],root:string):string=>{for(const x of xs){if(x.id===selected.id)return root;const hit=walk(x.children||[],x.name);if(hit)return hit}return ''};return walk(categories,'')},[categories,selected]);
 const fields:Field[]=selected&&!selected.children?.length?fallbackFields(selected.name,rootName):[];
 const run=async()=>{setLoading(true);try{const p=new URLSearchParams({limit:'48',sort,order:sort==='price'?'asc':'desc'});if(q.trim())p.set('q',q.trim());if(category)p.set('category',category);if(city!=='All Uganda')p.set('city',city);if(condition!=='Any')p.set('condition',condition);if(min)p.set('minPrice',min);if(max)p.set('maxPrice',max);Object.entries(attributeFilters).forEach(([k,v])=>{if(v)p.set('attr_'+k,v)});const d=await api<{items:Ad[]}>('/ads?'+p.toString());setAds(d.items||[])}catch{setAds([])}finally{setLoading(false);setRefresh(false)}};
 useEffect(()=>{api<Category[]>('/categories').then(x=>setCategories(Array.isArray(x)?x:[])).catch(()=>{});},[]);
 useEffect(()=>{run()},[category,city,condition,sort]);
 return <View style={s.screen}><View style={s.header}><Text style={s.title}>Search marketplace</Text><View style={s.search}><TextInput value={q} onChangeText={setQ} onSubmitEditing={run} placeholder="Search phones, cars, jobs..." placeholderTextColor="#8A94A6" style={s.input}/><Pressable onPress={run} style={s.go}><Text style={s.goText}>Search</Text></Pressable></View>
 <ScrollView horizontal showsHorizontalScrollIndicator={false} style={s.row}><Pressable onPress={()=>{setCategory('');setAttributeFilters({})}} style={[s.chip,!category&&s.active]}><Text style={[s.chipText,!category&&s.activeText]}>All categories</Text></Pressable>{all.filter(x=>!x.parentId).map(x=><Pressable key={x.id} onPress={()=>{setCategory(x.name);setAttributeFilters({})}} style={[s.chip,category===x.name&&s.active]}><Text style={[s.chipText,category===x.name&&s.activeText]}>{x.name}</Text></Pressable>)}</ScrollView>
 <ScrollView horizontal showsHorizontalScrollIndicator={false} style={s.row}>{cities.map(x=><Pressable key={x} onPress={()=>setCity(x)} style={[s.chip,x===city&&s.active]}><Text style={[s.chipText,x===city&&s.activeText]}>{x}</Text></Pressable>)}</ScrollView>
 <ScrollView horizontal showsHorizontalScrollIndicator={false} style={s.row}>{conditions.map(x=><Pressable key={x} onPress={()=>setCondition(x)} style={[s.chip,x===condition&&s.active]}><Text style={[s.chipText,x===condition&&s.activeText]}>{x}</Text></Pressable>)}</ScrollView>
 {fields.some(f=>f.type==='select')&&<ScrollView horizontal showsHorizontalScrollIndicator={false} style={s.row}>{fields.filter(f=>f.type==='select'&&f.options?.length).map(f=><View key={f.key} style={s.filterBox}><Text style={s.filterLabel}>{f.label}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{(f.options||[]).map(v=><Pressable key={v} onPress={()=>setAttributeFilters(x=>({...x,[f.key]:x[f.key]===v?'':v}))} style={[s.smallChip,attributeFilters[f.key]===v&&s.active]}><Text style={[s.smallText,attributeFilters[f.key]===v&&s.activeText]}>{v}</Text></Pressable>)}</ScrollView></View>)}</ScrollView>}
 <View style={s.priceRow}><TextInput value={min} onChangeText={setMin} keyboardType="numeric" placeholder="Min UGX" style={s.priceInput}/><TextInput value={max} onChangeText={setMax} keyboardType="numeric" placeholder="Max UGX" style={s.priceInput}/><Pressable onPress={run} style={s.filter}><Text style={s.filterText}>Apply</Text></Pressable><Pressable onPress={()=>setSort(sort==='createdAt'?'price':'createdAt')} style={s.sort}><Text style={s.sortText}>{sort==='price'?'Lowest price':'Newest'}</Text></Pressable></View></View>
 {loading&&!ads.length?<ActivityIndicator color={GREEN} style={{margin:30}}/>:<FlatList data={ads} numColumns={2} keyExtractor={x=>x.id} columnWrapperStyle={s.cols} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refresh} onRefresh={()=>{setRefresh(true);run()}} tintColor={GREEN}/>} ListHeaderComponent={<Text style={s.count}>{ads.length} result{ads.length===1?'':'s'}</Text>} renderItem={({item})=><AdCard ad={item}/>} ListEmptyComponent={<Text style={s.empty}>No matching adverts found.</Text>}/>}
 </View>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#F6F8F7'},header:{padding:16,paddingTop:24,backgroundColor:'#FFF',borderBottomWidth:1,borderBottomColor:'#E5EAE7'},title:{fontSize:22,fontWeight:'900',color:'#17202A',marginBottom:12},search:{flexDirection:'row',gap:7},input:{flex:1,height:48,borderRadius:12,borderWidth:1,borderColor:'#DCE4E0',paddingHorizontal:13,fontSize:14,color:'#17202A'},go:{backgroundColor:GREEN,borderRadius:12,paddingHorizontal:14,justifyContent:'center'},goText:{color:'#FFF',fontWeight:'900'},row:{marginTop:9},chip:{paddingHorizontal:10,paddingVertical:7,borderRadius:999,borderWidth:1,borderColor:'#DCE4E0',backgroundColor:'#FFF',marginRight:7},active:{backgroundColor:'#E8F6EF',borderColor:GREEN},chipText:{fontSize:10,color:'#64716C'},activeText:{color:GREEN,fontWeight:'900'},filterBox:{marginRight:10,maxWidth:310},filterLabel:{fontSize:10,fontWeight:'900',color:'#52605A',marginBottom:5},smallChip:{paddingHorizontal:9,paddingVertical:6,borderRadius:999,borderWidth:1,borderColor:'#DCE4E0',marginRight:5},smallText:{fontSize:9,color:'#64716C'},priceRow:{flexDirection:'row',gap:7,marginTop:9,alignItems:'center'},priceInput:{flex:1,height:42,borderWidth:1,borderColor:'#DCE4E0',borderRadius:10,paddingHorizontal:10},filter:{backgroundColor:'#17202A',borderRadius:10,paddingHorizontal:14,paddingVertical:12},filterText:{color:'#FFF',fontWeight:'800'},sort:{paddingHorizontal:6},sortText:{fontSize:10,fontWeight:'800',color:GREEN},content:{padding:12,paddingBottom:90},cols:{gap:10,marginBottom:10},count:{fontWeight:'800',color:'#5E6B76',marginBottom:12},empty:{textAlign:'center',paddingVertical:40,color:'#74808B'}});
