import { useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import AdCard from '@/components/AdCard';
import { api, type Ad } from '@/lib/api';
const GREEN='#0B8F55';
const cities=['All Uganda','Kampala','Wakiso','Mukono','Jinja','Mbarara'];
const conditions=['Any','NEW','USED','REFURBISHED'];
export default function SearchScreen(){
 const params=useLocalSearchParams<{q?:string}>();const[q,setQ]=useState(String(params.q||''));const[ads,setAds]=useState<Ad[]>([]);const[loading,setLoading]=useState(false);const[refresh,setRefresh]=useState(false);const[city,setCity]=useState('All Uganda');const[condition,setCondition]=useState('Any');const[min,setMin]=useState('');const[max,setMax]=useState('');const[sort,setSort]=useState('createdAt');
 const run=async()=>{setLoading(true);try{const p=new URLSearchParams({limit:'48',sort,order:sort==='price'?'asc':'desc'});if(q.trim())p.set('q',q.trim());if(city!=='All Uganda')p.set('city',city);if(condition!=='Any')p.set('condition',condition);if(min)p.set('minPrice',min);if(max)p.set('maxPrice',max);const d=await api<{items:Ad[]}>(`/ads?${p}`);setAds(d.items||[])}catch{setAds([])}finally{setLoading(false);setRefresh(false)}};
 useEffect(()=>{run()},[]);
 return <View style={s.screen}><View style={s.header}><Text style={s.title}>Search marketplace</Text><View style={s.search}><TextInput value={q} onChangeText={setQ} onSubmitEditing={run} placeholder="Search phones, cars, jobs..." placeholderTextColor="#8A94A6" style={s.input}/><Pressable onPress={run} style={s.go}><Text style={s.goText}>Search</Text></Pressable></View><View style={s.chips}>{cities.map(x=><Pressable key={x} onPress={()=>{setCity(x);setTimeout(run,0)}} style={[s.chip,x===city&&s.active]}><Text style={[s.chipText,x===city&&s.activeText]}>{x}</Text></Pressable>)}</View><View style={s.chips}>{conditions.map(x=><Pressable key={x} onPress={()=>{setCondition(x);setTimeout(run,0)}} style={[s.chip,x===condition&&s.active]}><Text style={[s.chipText,x===condition&&s.activeText]}>{x}</Text></Pressable>)}</View><View style={s.priceRow}><TextInput value={min} onChangeText={setMin} keyboardType="numeric" placeholder="Min UGX" style={s.priceInput}/><TextInput value={max} onChangeText={setMax} keyboardType="numeric" placeholder="Max UGX" style={s.priceInput}/><Pressable onPress={run} style={s.filter}><Text style={s.filterText}>Apply</Text></Pressable></View></View>{loading&&!ads.length?<ActivityIndicator color={GREEN} style={{margin:30}}/>:<FlatList data={ads} numColumns={2} keyExtractor={x=>x.id} columnWrapperStyle={s.cols} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refresh} onRefresh={()=>{setRefresh(true);run()}} tintColor={GREEN}/>} ListHeaderComponent={<View style={s.resultsHead}><Text style={s.count}>{ads.length} result{ads.length===1?'':'s'}</Text><Pressable onPress={()=>{setSort(sort==='createdAt'?'price':'createdAt');setTimeout(run,0)}}><Text style={s.sort}>Sort: {sort==='price'?'Price':'Newest'}</Text></Pressable></View>} renderItem={({item})=><AdCard ad={item}/>} ListEmptyComponent={<Text style={s.empty}>No matching adverts found.</Text>}/>}</View>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#F6F8F7'},header:{padding:16,paddingTop:24,backgroundColor:'#FFF',borderBottomWidth:1,borderBottomColor:'#E5EAE7'},title:{fontSize:22,fontWeight:'900',color:'#17202A',marginBottom:12},search:{flexDirection:'row',gap:7},input:{flex:1,height:48,borderRadius:12,borderWidth:1,borderColor:'#DCE4E0',paddingHorizontal:13,fontSize:14,color:'#17202A'},go:{backgroundColor:GREEN,borderRadius:12,paddingHorizontal:14,justifyContent:'center'},goText:{color:'#FFF',fontWeight:'900'},chips:{flexDirection:'row',gap:7,marginTop:9},chip:{paddingHorizontal:10,paddingVertical:7,borderRadius:999,borderWidth:1,borderColor:'#DCE4E0',backgroundColor:'#FFF'},active:{backgroundColor:'#E8F6EF',borderColor:GREEN},chipText:{fontSize:10,color:'#64716C'},activeText:{color:GREEN,fontWeight:'900'},priceRow:{flexDirection:'row',gap:7,marginTop:9},priceInput:{flex:1,height:42,borderWidth:1,borderColor:'#DCE4E0',borderRadius:10,paddingHorizontal:10},filter:{backgroundColor:'#17202A',borderRadius:10,paddingHorizontal:14,justifyContent:'center'},filterText:{color:'#FFF',fontWeight:'800'},content:{padding:12,paddingBottom:90},cols:{gap:10,marginBottom:10},resultsHead:{flexDirection:'row',justifyContent:'space-between',marginBottom:12},count:{fontWeight:'800',color:'#5E6B76'},sort:{fontSize:12,fontWeight:'800',color:GREEN},empty:{textAlign:'center',paddingVertical:40,color:'#74808B'}});
