import { Alert, Image, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useEffect, useMemo, useState } from 'react';
import { router } from 'expo-router';
import { api } from '@/lib/api';
import { fallbackFields, type Field } from '@/lib/category-fields';
import { useSession } from '@/lib/session';
const GREEN='#0B8F55';
type Cat={id:string;name:string;parentId?:string|null;children?:Cat[]}; type Picked={uri:string;name:string;type:string};
function flatten(nodes:Cat[],root='',out:{cat:Cat;root:string;depth:number}[]=[],depth=0){for(const c of nodes){out.push({cat:c,root:root||c.name,depth});if(c.children?.length)flatten(c.children,root||c.name,out,depth+1)}return out}
export default function SellScreen(){
 const{user,loading}=useSession();const[cats,setCats]=useState<Cat[]>([]);const[catOpen,setCatOpen]=useState(false);const[selected,setSelected]=useState<{cat:Cat;root:string}|null>(null);const[fields,setFields]=useState<Record<string,string>>({});
 const[images,setImages]=useState<Picked[]>([]);const[title,setTitle]=useState('');const[price,setPrice]=useState('');const[city,setCity]=useState('Kampala');const[description,setDescription]=useState('');const[condition,setCondition]=useState('USED');const[busy,setBusy]=useState(false);
 useEffect(()=>{if(!loading&&!user)router.replace({pathname:'/login',params:{next:'/(tabs)/sell'}})},[loading,user]);
 useEffect(()=>{api<Cat[]>('/categories').then(setCats).catch(()=>setCats([]))},[]);
 const allCats=useMemo(()=>flatten(cats),[cats]);const dynamic:Field[]=selected?fallbackFields(selected.cat.name,selected.root):[];
 if(loading)return <View style={styles.center}><Text style={styles.muted}>Loading�</Text></View>; if(!user)return <View style={styles.guest}><Image source={require('../../../assets/images/minify-market.png')} style={styles.guestLogo}/><Text style={styles.guestTitle}>Sign in to sell</Text><Text style={styles.muted}>Create an account or sign in to post your advert. After signing in, you will come straight back to Post an advert.</Text><Pressable style={styles.button} onPress={()=>router.push({pathname:'/login',params:{next:'/(tabs)/sell'}})}><Text style={styles.buttonText}>Sign in</Text></Pressable><Pressable style={styles.outlineButton} onPress={()=>router.push({pathname:'/register',params:{next:'/(tabs)/sell'}})}><Text style={styles.outlineButtonText}>Create account</Text></Pressable><Pressable onPress={()=>router.replace('/(tabs)')}><Text style={styles.backLink}>Continue browsing</Text></Pressable></View>;
 const pick=async()=>{const ImagePicker=await import('expo-image-picker');const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsMultipleSelection:true,selectionLimit:8,quality:0.85});if(!r.canceled)setImages(r.assets.map((a,i)=>({uri:a.uri,name:a.fileName||`image-${i}.jpg`,type:a.mimeType||'image/jpeg'})).slice(0,8))};
 const upload=async()=>{if(!images.length)return[];const form=new FormData();images.forEach(img=>form.append('images',{uri:img.uri,name:img.name,type:img.type} as any));const r=await api<{images:string[]}>('/uploads/images',{method:'POST',body:form});return r.images||[]};
 const submit=async()=>{if(!title||!price||!description||!selected)return Alert.alert('Missing information','Complete the title, price, category and description.');for(const f of dynamic.filter(x=>x.required)){if(!String(fields[f.key]||'').trim())return Alert.alert('Missing information',`${f.label} is required.`)}setBusy(true);try{const urls=await upload();const ad=await api<{id:string}>('/ads',{method:'POST',body:JSON.stringify({title,price:Number(price),description,city,categoryId:selected.cat.id,condition,negotiable:true,images:urls,attributes:fields})});await api(`/ads/${ad.id}/publish`,{method:'POST'});Alert.alert('Advert submitted','Your advert has been submitted for review.',[{text:'View advert',onPress:()=>router.push(`/ad/${ad.id}`)}]);}catch(e:any){Alert.alert('Could not post advert',e?.message||'Please try again.')}finally{setBusy(false)}};
 return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.h1}>Post an advert</Text><Text style={styles.muted}>Add clear photos and complete only the useful fields for your category.</Text>
 <Field label="Title" value={title} onChangeText={setTitle} placeholder="e.g. iPhone 16 Pro 256GB"/><Field label="Price (UGX)" value={price} onChangeText={setPrice} placeholder="3300000" keyboardType="numeric"/><Text style={styles.label}>Category</Text><Pressable style={styles.selector} onPress={()=>setCatOpen(true)}><Text style={selected?styles.selectorText:styles.placeholder}>{selected?.cat.name||'Choose a category'}</Text><Text style={styles.arrow}>›</Text></Pressable>
 <Text style={styles.label}>Photos (up to 8)</Text><Pressable style={styles.photoButton} onPress={pick}><Text style={styles.photoButtonText}>Choose photos</Text></Pressable>
 {images.length>0&&<ScrollView horizontal style={{marginTop:9}}>{images.map((x,i)=><View key={x.uri} style={styles.photoWrap}><Image source={{uri:x.uri}} style={styles.photo}/><Pressable onPress={()=>setImages(images.filter((_,n)=>n!==i))} style={styles.remove}><Text style={styles.removeText}>×</Text></Pressable></View>)}</ScrollView>}
 <Field label="City" value={city} onChangeText={setCity} placeholder="Kampala"/><Text style={styles.label}>Condition</Text><View style={styles.choices}>{['NEW','USED','REFURBISHED'].map(x=><Choice key={x} text={x} active={condition===x} onPress={()=>setCondition(x)}/>)}</View>
 {dynamic.map(f=><DynamicField key={f.key} field={f} value={fields[f.key]||''} onChange={v=>setFields({...fields,[f.key]:v})}/>)}
 <Field label="Description" value={description} onChangeText={setDescription} placeholder="Describe the item, condition, location and what is included" multiline/><Pressable disabled={busy} style={styles.button} onPress={submit}><Text style={styles.buttonText}>{busy?'Posting…':'Post advert'}</Text></Pressable>
 <Modal visible={catOpen} animationType="slide" onRequestClose={()=>setCatOpen(false)}><View style={styles.modal}><View style={styles.modalHead}><Text style={styles.modalTitle}>Choose category</Text><Pressable onPress={()=>setCatOpen(false)}><Text style={styles.close}>Close</Text></Pressable></View><ScrollView>{allCats.map(({cat,root,depth})=><Pressable key={cat.id} style={[styles.catRow,{paddingLeft:16+depth*16}]} onPress={()=>{setSelected({cat,root});setFields({});setCatOpen(false)}}><Text style={[styles.catText,depth===0&&styles.rootText]}>{cat.name}</Text></Pressable>)}</ScrollView></View></Modal></ScrollView>}
function DynamicField({field,value,onChange}:{field:Field;value:string;onChange:(v:string)=>void}){if(field.type==='select')return <View><Text style={styles.label}>{field.label}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:7}}>{(field.options||[]).map((o:string)=><Pressable key={o} onPress={()=>onChange(o)} style={[styles.choice,value===o&&styles.choiceActive]}><Text style={[styles.choiceText,value===o&&styles.choiceTextActive]}>{o}</Text></Pressable>)}</ScrollView></View>;return <Field label={field.label} value={value} onChangeText={onChange} placeholder={field.placeholder||''} keyboardType={field.type==='number'?'numeric':'default'}/>}
function Field({label,multiline=false,...props}:any){return <View><Text style={styles.label}>{label}</Text><TextInput {...props} multiline={multiline} style={[styles.input,multiline&&styles.textarea]} placeholderTextColor="#8A94A6"/></View>}
function Choice({text,active,onPress}:{text:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.choice,active&&styles.choiceActive]}><Text style={[styles.choiceText,active&&styles.choiceTextActive]}>{text}</Text></Pressable>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#F6F8F7'},content:{padding:18,paddingBottom:100},h1:{fontSize:28,fontWeight:'900',color:'#17202A',marginTop:10},muted:{color:'#73808A',lineHeight:21,marginVertical:10},label:{fontSize:13,fontWeight:'800',color:'#44515C',marginTop:14,marginBottom:7},input:{height:52,backgroundColor:'#FFF',borderWidth:1,borderColor:'#DCE4E0',borderRadius:12,paddingHorizontal:14,fontSize:15,color:'#17202A'},textarea:{height:130,paddingTop:14,textAlignVertical:'top'},selector:{height:52,backgroundColor:'#FFF',borderWidth:1,borderColor:'#DCE4E0',borderRadius:12,paddingHorizontal:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},selectorText:{color:'#17202A',fontWeight:'700'},placeholder:{color:'#8A94A6'},arrow:{fontSize:30,color:GREEN,lineHeight:30},photoButton:{height:48,borderRadius:12,borderWidth:1,borderColor:GREEN,backgroundColor:'#E8F6EF',alignItems:'center',justifyContent:'center'},photoButtonText:{color:GREEN,fontWeight:'900'},photoWrap:{marginRight:8,position:'relative'},photo:{width:78,height:78,borderRadius:10,backgroundColor:'#EAF0ED'},remove:{position:'absolute',right:3,top:3,width:23,height:23,borderRadius:12,backgroundColor:'#17202A',alignItems:'center',justifyContent:'center'},removeText:{color:'#FFF',fontSize:18,lineHeight:20},choices:{flexDirection:'row',gap:7,flexWrap:'wrap'},choice:{paddingHorizontal:13,paddingVertical:10,borderRadius:999,backgroundColor:'#FFF',borderWidth:1,borderColor:'#DCE4E0'},choiceActive:{backgroundColor:'#E8F6EF',borderColor:GREEN},choiceText:{fontWeight:'800',fontSize:12,color:'#66727D'},choiceTextActive:{color:GREEN},button:{height:54,backgroundColor:GREEN,borderRadius:13,alignItems:'center',justifyContent:'center',marginTop:20},buttonText:{color:'#FFF',fontWeight:'900',fontSize:16},center:{flex:1,padding:24,justifyContent:'center',alignItems:'center',backgroundColor:'#F6F8F7'},guest:{flex:1,padding:28,justifyContent:'center',backgroundColor:'#FFF'},guestLogo:{width:190,height:70,resizeMode:'contain',alignSelf:'center',marginBottom:22},guestTitle:{fontSize:29,fontWeight:'900',color:'#17202A'},outlineButton:{height:54,borderRadius:13,borderWidth:1,borderColor:GREEN,alignItems:'center',justifyContent:'center',marginTop:10},outlineButtonText:{color:GREEN,fontWeight:'900',fontSize:16},backLink:{textAlign:'center',marginTop:20,color:'#6F91A2',fontWeight:'700'},modal:{flex:1,backgroundColor:'#F6F8F7',paddingTop:55},modalHead:{height:62,paddingHorizontal:18,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#FFF',borderBottomWidth:1,borderBottomColor:'#E2E8E5'},modalTitle:{fontSize:21,fontWeight:'900',color:'#17202A'},close:{color:GREEN,fontWeight:'900'},catRow:{minHeight:50,justifyContent:'center',borderBottomWidth:1,borderBottomColor:'#E9EEEB',backgroundColor:'#FFF'},catText:{fontSize:14,color:'#34414C'},rootText:{fontWeight:'900',fontSize:15,color:'#17202A'}});
