import { ActivityIndicator, Image, Pressable, ScrollView, Share, StyleSheet, Text, View } from 'react-native';
import { useEffect, useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { api, mediaUrl, type Ad } from '@/lib/api';
import { useSession } from '@/lib/session';
const GREEN='#0B8F55';
export default function Seller(){
 const {id}=useLocalSearchParams<{id:string}>();const{user}=useSession();const[seller,setSeller]=useState<any>(null);const[ads,setAds]=useState<Ad[]>([]);const[reviews,setReviews]=useState<any[]>([]);const[following,setFollowing]=useState(false);const[loading,setLoading]=useState(true);
 useEffect(()=>{if(!id)return;(async()=>{try{const[s,a,r]=await Promise.all([api<any>(`/users/${id}`),api<{items:Ad[]}>(`/ads?sellerId=${id}&limit=24`),api<any[]>(`/reviews/seller/${id}`)]);setSeller(s);setAds(a.items||[]);setReviews(r||[]);if(user)try{const f=await api<any>(`/users/me/following/${id}`);setFollowing(!!f.following)}catch{}}finally{setLoading(false)}})()},[id,user]);
 if(loading)return <View style={s.center}><ActivityIndicator color={GREEN}/></View>;if(!seller)return <View style={s.center}><Text>Seller not found.</Text></View>;
 const avg=reviews.length?reviews.reduce((x,r)=>x+Number(r.rating||0),0)/reviews.length:0;
 const follow=async()=>{if(!user){router.push({pathname:'/login',params:{next:`/seller/${id}`}});return}try{const r=await api<any>(`/users/me/following/${id}`,{method:'POST'});setFollowing(!!r.following)}catch{}};
 const share=async()=>{try{await Share.share({message:`View ${seller.name||'this seller'} on MINIFY MARKET`})}catch{}};
 return <ScrollView style={s.screen} contentContainerStyle={s.content}><View style={s.top}><Pressable onPress={()=>router.back()}><Ionicons name="arrow-back" size={25} color="#17202A"/></Pressable><Text style={s.topTitle}>Seller profile</Text><Pressable onPress={share}><Ionicons name="share-social-outline" size={22} color="#17202A"/></Pressable></View><View style={s.profile}><View style={s.avatar}><Ionicons name="person" size={34} color={GREEN}/></View><Text style={s.name}>{seller.name||'Marketplace seller'} {seller.verified?'✓':''}</Text><Text style={s.meta}>{seller.city||'Uganda'} · Member since {seller.createdAt?new Date(seller.createdAt).toLocaleDateString():'recently'}</Text><View style={s.rating}><Ionicons name="star" size={17} color="#E5A900"/><Text>{avg?avg.toFixed(1):'New seller'} · {reviews.length} review{reviews.length===1?'':'s'}</Text></View><View style={s.actions}><Pressable style={s.primary} onPress={()=>ads[0]&&router.push(`/ad/${ads[0].id}`)}><Text style={s.primaryText}>View listings</Text></Pressable><Pressable style={s.outline} onPress={follow}><Text style={s.outlineText}>{following?'Following':'Follow'}</Text></Pressable></View></View><View style={s.trust}><Text>🛡 {seller.verified?'Identity verified':'Marketplace profile'}</Text><Text>📍 {seller.city||'Uganda'}</Text><Text>📦 {ads.length} active adverts</Text></View><Text style={s.section}>Active adverts</Text>{ads.length?<View style={s.grid}>{ads.map(a=><Pressable key={a.id} style={s.card} onPress={()=>router.push(`/ad/${a.id}`)}><View style={s.image}>{a.images?.[0]?.url?<Image source={{uri:mediaUrl(a.images[0].url)}} style={s.image}/>:<Text style={s.mm}>MM</Text>}</View><Text numberOfLines={2} style={s.cardTitle}>{a.title}</Text><Text style={s.price}>UGX {Number(a.price).toLocaleString()}</Text></Pressable>)}</View>:<Text style={s.meta}>No active adverts.</Text>}<Text style={s.section}>Buyer feedback</Text>{reviews.length?reviews.map(r=><View key={r.id} style={s.review}><Text style={s.stars}>{'★'.repeat(Number(r.rating||0))}{'☆'.repeat(5-Number(r.rating||0))}</Text><Text style={s.reviewName}>{r.reviewer?.name||'Buyer'}</Text><Text style={s.meta}>{r.comment||'No written comment.'}</Text></View>):<Text style={s.meta}>No reviews yet.</Text>}</ScrollView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#F6F8F7'},content:{paddingBottom:100},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#F6F8F7'},top:{height:58,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#FFF',borderBottomWidth:1,borderBottomColor:'#E1E8E4'},topTitle:{fontWeight:'900',fontSize:17,color:'#17202A'},profile:{padding:22,alignItems:'center',backgroundColor:'#FFF'},avatar:{width:78,height:78,borderRadius:39,backgroundColor:'#E8F6EF',alignItems:'center',justifyContent:'center'},name:{fontSize:22,fontWeight:'900',color:'#17202A',marginTop:10},meta:{fontSize:12,color:'#74808B',lineHeight:19,marginTop:3},rating:{flexDirection:'row',alignItems:'center',gap:5,marginTop:7},actions:{flexDirection:'row',gap:8,marginTop:15},primary:{backgroundColor:GREEN,paddingHorizontal:20,paddingVertical:12,borderRadius:11},primaryText:{color:'#FFF',fontWeight:'900'},outline:{borderWidth:1,borderColor:GREEN,paddingHorizontal:20,paddingVertical:12,borderRadius:11},outlineText:{color:GREEN,fontWeight:'900'},trust:{margin:12,padding:13,borderRadius:13,backgroundColor:'#E8F6EF',gap:5},section:{fontSize:19,fontWeight:'900',color:'#17202A',paddingHorizontal:16,marginTop:14,marginBottom:9},grid:{flexDirection:'row',flexWrap:'wrap',gap:10,paddingHorizontal:12},card:{width:'47.5%',backgroundColor:'#FFF',borderRadius:13,borderWidth:1,borderColor:'#E1E8E4',paddingBottom:10,overflow:'hidden'},image:{width:'100%',height:125,backgroundColor:'#EEF2F0',alignItems:'center',justifyContent:'center'},mm:{fontWeight:'900',color:GREEN},cardTitle:{fontSize:13,fontWeight:'800',color:'#17202A',paddingHorizontal:9,marginTop:7},price:{fontSize:14,fontWeight:'900',color:GREEN,paddingHorizontal:9,marginTop:5},review:{marginHorizontal:16,marginBottom:8,padding:13,borderRadius:12,backgroundColor:'#FFF',borderWidth:1,borderColor:'#E1E8E4'},stars:{color:'#E5A900',marginBottom:4},reviewName:{fontWeight:'900',color:'#17202A'}});
