'use client';
import {useEffect,useState} from 'react';
import Header from '../../components/Header';
import {API,api,mediaUrl,money} from '../../lib';
import Link from 'next/link';
import {BadgeCheck,Star,MapPin,MessageCircle,Phone,ShieldCheck,Package,UserRound,UserPlus,Share2} from 'lucide-react';
export default function SellerPage({params}:{params:Promise<{id:string}>}){
 const [id,setId]=useState(''),[seller,setSeller]=useState<any>(null),[ads,setAds]=useState<any[]>([]),[reviews,setReviews]=useState<any[]>([]),[following,setFollowing]=useState(false),[err,setErr]=useState('');
 useEffect(()=>{params.then(p=>setId(p.id))},[params]);
 useEffect(()=>{if(!id)return;Promise.all([fetch(`${API}/users/${id}`).then(r=>r.ok?r.json():null),api(`/ads?sellerId=${id}`).catch(()=>({items:[]})),api(`/reviews/seller/${id}`).catch(()=>[])]).then(([s,a,r])=>{setSeller(s);setAds(Array.isArray(a)?a:(a?.items||[]));setReviews(Array.isArray(r)?r:[])}).catch(e=>setErr(e.message||'Could not load seller profile.'))},[id]);
 const avg=reviews.length?reviews.reduce((x,r)=>x+Number(r.rating||0),0)/reviews.length:0; const stars=Math.max(0,Math.min(5,Math.round(avg)));
 async function chat(){const raw=localStorage.getItem('minify_user');if(!raw){location.href='/login?next=/seller/'+id;return}const u=JSON.parse(raw);if(u.id===id)return;const a=ads[0];if(!a){location.href='/messages';return}try{const c=await api('/chats/conversation',{method:'POST',body:JSON.stringify({adId:a.id,buyerId:u.id,sellerId:id})});location.href='/messages?conversation='+c.id}catch(e:any){setErr(e.message||'Could not start conversation.')}}
 const canChat=ads.length>0&&seller?.id!==id;
 useEffect(()=>{if(!id||!localStorage.getItem('minify_token'))return;api(`/users/me/following/${id}`).then((x:any)=>setFollowing(!!x.following)).catch(()=>{})},[id]);
 async function toggleFollow(){if(!localStorage.getItem('minify_token')){location.href='/login?next=/seller/'+id;return}try{const x=await api(`/users/me/following/${id}`,{method:'POST'});setFollowing(!!x.following);setSeller((s:any)=>s?{...s,followers:Math.max(0,Number(s.followers||0)+(x.following?1:-1))}:s)}catch(e:any){setErr(e.message||'Could not update seller follow status.')}}
 async function shareSeller(){const url=location.href;try{if(navigator.share)await navigator.share({title:seller?.name||'MINIFY MARKET seller',text:`View ${seller?.name||'this seller'} on MINIFY MARKET`,url});else{await navigator.clipboard.writeText(url);setErr('Seller profile link copied.')}}catch(e:any){if(e?.name!=='AbortError')setErr('Could not share seller profile.')}}
 return <><Header/><main className="page-shell">{err&&<div className="notice">{err}</div>}{seller?<>
 <section className="surface seller-profile-v2"><div className="seller-avatar-v2">{seller.avatarUrl?<img src={mediaUrl(seller.avatarUrl)} alt=""/>:<UserRound size={32}/>}</div><div className="seller-info-v2"><h1>{seller.name||'Marketplace seller'} {seller.verified&&<BadgeCheck size={22} color="var(--green)"/>}</h1><div className="seller-meta-v2"><span><MapPin size={15}/> {seller.city||'Uganda'}</span><span>•</span><span>Member since {seller.createdAt?new Date(seller.createdAt).toLocaleDateString():'Recently'}</span></div><div className="seller-rating-v2"><Star size={17} fill="currentColor"/> <b>{avg?avg.toFixed(1):'New seller'}</b>{avg>0&&<span className="review-stars">{'★'.repeat(stars)}{'☆'.repeat(5-stars)}</span>}<span>({reviews.length} review{reviews.length===1?'':'s'})</span></div></div><div className="seller-actions-v2">{canChat&&<button className="btn primary" onClick={chat}><MessageCircle size={17}/> Chat seller</button>}{seller.phone&&<a className="btn outline" href={'tel:'+seller.phone}><Phone size={17}/> Call seller</a>}<button className="btn outline" onClick={toggleFollow}><UserPlus size={17}/> {following?'Following':'Follow seller'}</button><button className="btn outline" onClick={shareSeller}><Share2 size={17}/> Share</button></div><div className="seller-stat-row"><div className="seller-stat"><b>{ads.length}</b><span>Active adverts</span></div><div className="seller-stat"><b>{Number(seller.followers||0)}</b><span>Followers</span></div><div className="seller-stat"><b>{reviews.length}</b><span>Buyer reviews</span></div></div></section>
 <div className="trust-strip-v2"><span><ShieldCheck size={14}/> {seller.verified?'Identity verified':'Marketplace profile'}</span><span><Package size={14}/> Active listings checked</span><span><MapPin size={14}/> {seller.city||'Uganda'}</span></div>
 <section className="seller-section"><div className="seller-section-head"><div><span className="eyebrow">SELLER LISTINGS</span><h2>Active adverts</h2></div><span className="muted">{ads.length} available</span></div>{ads.length?<div className="grid">{ads.map(a=><Link className="listing" key={a.id} href={'/ad/'+a.id}><div className="listing-image"><img src={mediaUrl(a.images?.[0]?.url||'/minify-market-official.png')} alt={a.title||''}/></div><div className="listing-body"><div className="price">{money(a.price)}</div><b className="listing-title">{a.title}</b><span className="muted">{a.city||'Uganda'}</span></div></Link>)}</div>:<div className="surface surface-pad empty"><Package size={34}/><h3>No active adverts</h3><p className="muted">This seller does not have any active adverts right now.</p><Link href="/ads" className="btn primary">Browse marketplace</Link></div>}</section>
 <section className="surface surface-pad seller-section"><div className="seller-section-head"><div><span className="eyebrow">BUYER FEEDBACK</span><h2>Reviews from buyers</h2></div></div>{reviews.length?<div className="review-list">{reviews.map(r=><article className="review-v2" key={r.id}><div className="review-stars" aria-label={`${r.rating} out of 5 stars`}>{'★'.repeat(Number(r.rating||0))}{'☆'.repeat(5-Number(r.rating||0))}</div><b>{r.reviewer?.name||'Buyer'}</b><p>{r.comment||'No written comment.'}</p></article>)}</div>:<div className="empty"><Star size={30}/><h3>No reviews yet</h3><p className="muted">Buyer feedback will appear here after completed transactions.</p></div>}</section>
 </>:<div className="surface surface-pad empty"><UserRound size={34}/><h2>Loading seller profile...</h2></div>}</main></>;
}