'use client';
import Header from '../components/Header';
import Link from 'next/link';
import {ChevronDown,ShieldCheck,MessageCircle,ShoppingBag} from 'lucide-react';
import {useState} from 'react';
const faqs=[
 ['How do I buy an item?','Open an advert, review the seller and item details, then use the contact or order option shown on the advert. Confirm the price, condition and meeting or delivery arrangement before paying.'],
 ['How do I post an advert?','Select Sell, choose the closest category, complete the category-specific details, add clear photos, set your price and submit. Adverts go through the marketplace review flow before becoming active.'],
 ['How do I stay safe?','Meet in a sensible public place where practical, inspect the item before completing a transaction, and never share passwords or verification codes. Report suspicious adverts or behaviour to MINIFY MARKET.'],
 ['How do saved adverts and searches work?','Use the heart on an advert to save it. You can also save a search so you can return to the same search criteria from your account centre.'],
 ['What does seller verification mean?','Verification is a marketplace trust signal. Sellers can request verification from their account area, and the marketplace can review the request before marking the account verified.'],
 ['How do promotions work?','Eligible sellers can promote active adverts from the promotion centre. Promotion payments and campaign status are shown in the seller tools.'],
 ['What if I have a problem with an advert?','Use the report option on the advert and provide a clear reason and useful details. Marketplace staff can review submitted reports.'],
 ['How do I contact support?','Use the marketplace messaging tools for transaction conversations. For account or safety issues, use the support contact provided by the marketplace operator.']
];
export default function Help(){const[open,setOpen]=useState<number|null>(0);return <><Header/><main className="page-shell"><div className="page-title"><span className="eyebrow">MINIFY MARKET SUPPORT</span><h1>Help & FAQ</h1><p className="muted">Quick answers for buying, selling, account safety and marketplace tools.</p></div><div className="help-grid"><section className="surface surface-pad"><div className="surface-head"><div><h2>Frequently asked questions</h2><p className="muted">Everything you need for the common marketplace flows.</p></div></div><div className="faq-list">{faqs.map(([q,a],i)=><div className={'faq-item '+(open===i?'open':'')} key={q}><button className="faq-question" onClick={()=>setOpen(open===i?null:i)} aria-expanded={open===i}><span>{q}</span><ChevronDown size={18}/></button>{open===i&&<div className="faq-answer">{a}</div>}</div>)}</div></section><aside className="surface surface-pad help-aside"><div className="help-card"><ShieldCheck size={22}/><h3>Trade with confidence</h3><p>Check item details, communicate through the marketplace and use reporting tools when something looks wrong.</p></div><div className="help-card"><ShoppingBag size={22}/><h3>Buying & selling</h3><p>Explore categories, compare adverts, save searches and manage your own listings from one account centre.</p></div><div className="help-card"><MessageCircle size={22}/><h3>Need more help?</h3><p>For an issue involving a specific transaction or advert, keep the relevant advert and conversation details available when contacting support.</p></div><Link className="btn primary" href="/">Back to marketplace</Link></aside></div></main></>}
