import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
const GREEN='#0B8F55';
export default function JobsScreen(){return <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
 <View style={styles.header}><Pressable onPress={()=>router.back()}><Ionicons name="arrow-back" size={27} color="#34434D"/></Pressable><Text style={styles.headerTitle}>Jobs & CVs</Text></View>
 <View style={styles.hero}><Text style={styles.kicker}>MINIFY MARKET</Text><Text style={styles.title}>Find opportunities or talent</Text><Text style={styles.sub}>Browse local jobs and people offering their skills across Uganda.</Text></View>
 <Pressable style={styles.card} onPress={()=>router.push({pathname:'/search',params:{q:'Jobs'}})}><View style={styles.icon}><Ionicons name="briefcase-outline" size={25} color={GREEN}/></View><View style={styles.copy}><Text style={styles.cardTitle}>Jobs</Text><Text style={styles.cardSub}>Find vacancies, roles and local opportunities.</Text></View><Ionicons name="chevron-forward" size={20} color="#82908A"/></Pressable>
 <Pressable style={styles.card} onPress={()=>router.push({pathname:'/search',params:{q:'Seeking Work CVs'}})}><View style={styles.icon}><Ionicons name="document-text-outline" size={25} color={GREEN}/></View><View style={styles.copy}><Text style={styles.cardTitle}>CVs & people seeking work</Text><Text style={styles.cardSub}>Discover people offering professional skills and services.</Text></View><Ionicons name="chevron-forward" size={20} color="#82908A"/></Pressable>
 <Pressable style={styles.sell} onPress={()=>router.push('/sell')}><Text style={styles.sellText}>Post a job or CV</Text><Ionicons name="arrow-forward" size={19} color="#FFF"/></Pressable>
 </ScrollView>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#F6F8F7'},content:{padding:16,paddingBottom:100},header:{height:58,flexDirection:'row',alignItems:'center',gap:12},headerTitle:{fontSize:21,fontWeight:'900',color:'#17202A'},hero:{backgroundColor:'#073F36',borderRadius:20,padding:24,marginBottom:15},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.6,color:'#9CEBD5'},title:{fontSize:28,fontWeight:'900',color:'#FFF',marginTop:7,lineHeight:33},sub:{fontSize:13,color:'#D4EEE7',lineHeight:20,marginTop:7},card:{backgroundColor:'#FFF',borderRadius:16,borderWidth:1,borderColor:'#E0E8E4',padding:16,marginBottom:10,flexDirection:'row',alignItems:'center',gap:12},icon:{width:48,height:48,borderRadius:14,backgroundColor:'#E8F6F0',alignItems:'center',justifyContent:'center'},copy:{flex:1},cardTitle:{fontSize:15,fontWeight:'900',color:'#17202A'},cardSub:{fontSize:12,color:'#74808B',lineHeight:18,marginTop:3},sell:{height:52,borderRadius:13,backgroundColor:GREEN,marginTop:8,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},sellText:{color:'#FFF',fontSize:15,fontWeight:'900'}});
