import { Alert, Image, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { useSession } from '@/lib/session';
const GREEN='#0B8F55';
export default function Login(){
 const {login}=useSession();const {next}=useLocalSearchParams<{next?:string}>();const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[busy,setBusy]=useState(false);
 const submit=async()=>{if(!email||!password)return Alert.alert('Missing information','Enter your email and password.');setBusy(true);try{await login(email,password,next)}catch(e:any){Alert.alert('Login failed',e?.message||'Please try again.')}finally{setBusy(false)}};
 return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS==='ios'?'padding':undefined}><View style={styles.box}><Image source={require('../../assets/images/minify-market.png')} style={styles.logo}/><Text style={styles.h1}>Sign in</Text><Text style={styles.muted}>Buy, sell, save adverts and message sellers.</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="Email or phone" placeholderTextColor="#8A94A6" style={styles.input}/><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Password" placeholderTextColor="#8A94A6" style={styles.input}/><Pressable disabled={busy} onPress={submit} style={styles.button}><Text style={styles.buttonText}>{busy?'Signing in…':'Sign in'}</Text></Pressable><Pressable onPress={()=>router.push({pathname:'/register',params:next?{next}:undefined})}><Text style={styles.link}>Don't have an account? <Text style={styles.green}>Create account</Text></Text></Pressable><Pressable onPress={()=>router.back()}><Text style={styles.back}>Continue browsing</Text></Pressable></View></KeyboardAvoidingView>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#FFF',justifyContent:'center'},box:{padding:28},logo:{width:175,height:62,resizeMode:'contain',alignSelf:'center',marginBottom:22},h1:{fontSize:28,fontWeight:'800',color:'#34434D'},muted:{color:'#7892A2',marginVertical:9,fontSize:15},input:{height:54,backgroundColor:'#FFF',borderRadius:8,borderWidth:1,borderColor:'#D3DEE4',paddingHorizontal:15,color:'#34434D',marginTop:10},button:{height:56,backgroundColor:GREEN,borderRadius:8,alignItems:'center',justifyContent:'center',marginTop:15},buttonText:{color:'#FFF',fontWeight:'800',fontSize:17},link:{color:'#8EA9B9',textAlign:'center',marginTop:22,fontSize:15},green:{color:GREEN,fontWeight:'800'},back:{color:'#64717C',fontWeight:'700',textAlign:'center',marginTop:20}});
