import { Alert, Image, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { useSession } from '@/lib/session';
const GREEN='#0B8F55';
export default function Register(){
 const{register}=useSession();const{next}=useLocalSearchParams<{next?:string}>();const[name,setName]=useState('');const[email,setEmail]=useState('');const[phone,setPhone]=useState('');const[password,setPassword]=useState('');const[busy,setBusy]=useState(false);
 const submit=async()=>{if(!name||!email||!phone||!password)return Alert.alert('Missing information','Complete all fields.');if(password.length<8)return Alert.alert('Password','Use at least 8 characters.');setBusy(true);try{await register(name,email,phone,password,next)}catch(e:any){Alert.alert('Registration failed',e?.message||'Please try again.')}finally{setBusy(false)}};
 return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={styles.box}><Image source={require('../../assets/images/minify-market.png')} style={styles.logo}/><Text style={styles.h1}>Create your account</Text><Text style={styles.muted}>Create an account to sell, save and message on MINIFY MARKET.</Text><Field value={name} onChangeText={setName} placeholder="Full name"/><Field value={email} onChangeText={setEmail} placeholder="Email" autoCapitalize="none" keyboardType="email-address"/><Field value={phone} onChangeText={setPhone} placeholder="Phone number" keyboardType="phone-pad"/><Field value={password} onChangeText={setPassword} placeholder="Password (8+ characters)" secureTextEntry/><Pressable disabled={busy} onPress={submit} style={styles.button}><Text style={styles.buttonText}>{busy?'Creating…':'Create account'}</Text></Pressable><Pressable onPress={()=>router.push({pathname:'/login',params:next?{next}:undefined})}><Text style={styles.link}>Already have an account? <Text style={styles.green}>Sign in</Text></Text></Pressable></ScrollView></KeyboardAvoidingView>}
function Field(props:any){return <TextInput {...props} placeholderTextColor="#8A94A6" style={styles.input}/>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#FFF'},box:{padding:28,paddingTop:60,paddingBottom:50},logo:{width:175,height:62,resizeMode:'contain',alignSelf:'center',marginBottom:22},h1:{fontSize:28,fontWeight:'800',color:'#34434D'},muted:{color:'#7892A2',lineHeight:21,marginVertical:8},input:{height:54,backgroundColor:'#FFF',borderRadius:8,borderWidth:1,borderColor:'#D3DEE4',paddingHorizontal:15,color:'#34434D',marginTop:10},button:{height:56,backgroundColor:GREEN,borderRadius:8,alignItems:'center',justifyContent:'center',marginTop:15},buttonText:{color:'#FFF',fontWeight:'800',fontSize:17},link:{color:'#8EA9B9',textAlign:'center',marginTop:22,fontSize:15},green:{color:GREEN,fontWeight:'800'}});
