'use client';
import {useState} from 'react';
import {api} from '../lib';

export default function PayoutSetup({user,onDone}:{user:any,onDone?:(x:any)=>void}){
 const [bank,setBank]=useState(''),[account,setAccount]=useState(''),[branch,setBranch]=useState(''),[business,setBusiness]=useState(user?.name||''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 if(user?.flutterwaveSubaccountStatus==='ACTIVE')return <section className="surface surface-pad"><div className="surface-head"><div><h2>Seller payouts</h2><p className="muted">Your Flutterwave seller settlement account is connected.</p></div><span className="badge">Connected</span></div><div className="security-callout">Payments for your marketplace sales can be split securely to your configured settlement account.</div></section>;
 async function save(e:any){e.preventDefault();setBusy(true);setMsg('');try{const x=await api('/users/me/flutterwave-subaccount',{method:'POST',body:JSON.stringify({accountBank:bank,accountNumber:account,branchCode:branch,businessName:business})});setMsg(x.message||'Payout account connected.');onDone?.({...user,flutterwaveSubaccountStatus:x.status});}catch(e:any){setMsg(e?.message||'Could not connect payout account.')}finally{setBusy(false)}}
 return <section className="surface surface-pad"><div className="surface-head"><div><h2>Seller payouts</h2><p className="muted">Connect the bank account where your share of marketplace sales will settle.</p></div></div><div className="security-callout">Your bank account number is sent to Flutterwave for verification and is not stored by MINIFY MARKET.</div><form className="profile-form" onSubmit={save}><label>Bank code<input value={bank} onChange={e=>setBank(e.target.value)} placeholder="Flutterwave bank code" required/></label><label>Bank account number<input value={account} onChange={e=>setAccount(e.target.value)} inputMode="numeric" required/></label><label>Branch code<input value={branch} onChange={e=>setBranch(e.target.value)} placeholder="Uganda branch code" required/></label><label>Business / seller name<input value={business} onChange={e=>setBusiness(e.target.value)} required maxLength={120}/></label><div className="profile-actions"><button className="btn primary" disabled={busy}>{busy?'Connecting...':'Connect secure payouts'}</button>{msg&&<span className="form-help">{msg}</span>}</div></form></section>;
}
