'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import Header from '../components/Header';
import ImageUploader from '../components/ImageUploader';
import { API, api } from '../lib';
import {REGIONS,DISTRICTS,COLORS,PHONE_BRANDS,PHONE_MODELS,CAR_MAKES,BODY_TYPES,TRANSMISSIONS,FUEL_TYPES,NETWORKS,SIM_OPTIONS,VEHICLE_MODELS,LAPTOP_BRANDS,PROCESSORS,SCREEN_SIZES,VEHICLE_CONDITIONS,DRIVETRAINS,PHONE_FEATURES} from './catalog';

type Category={id:string;name:string;slug:string;parentId:string|null;children?:Category[]};
type Field={key:string;label:string;type:'text'|'number'|'select'|'textarea';options?:string[];required?:boolean;placeholder?:string};

const FIELD_RULES:Record<string,Field[]>= {
 'Mobile Phones':[{key:'brand',label:'Brand',type:'select',options:PHONE_BRANDS,required:true},{key:'model',label:'Model',type:'select',options:[],required:true},{key:'storage',label:'Internal storage',type:'select',options:['32 GB','64 GB','128 GB','256 GB','512 GB','1 TB','2 TB'],required:true},{key:'ram',label:'RAM',type:'select',options:['1 GB','2 GB','3 GB','4 GB','6 GB','8 GB','12 GB','16 GB','24 GB'],required:true},{key:'color',label:'Color',type:'select',options:COLORS,required:true},{key:'network',label:'Network',type:'select',options:NETWORKS,required:true},{key:'sim',label:'SIM',type:'select',options:SIM_OPTIONS,required:true}],
 'Tablets':[{key:'brand',label:'Brand',type:'text',required:true},{key:'model',label:'Model',type:'text',required:true},{key:'storage',label:'Storage',type:'select',options:['32 GB','64 GB','128 GB','256 GB','512 GB','1 TB'],required:true},{key:'screenSize',label:'Screen size',type:'text',placeholder:'e.g. 10.9 inch'}],
 'Smart Watches':[{key:'brand',label:'Brand',type:'text',required:true},{key:'model',label:'Model',type:'text',required:true},{key:'compatibility',label:'Compatibility',type:'select',options:['Android','iPhone / iOS','Android & iOS'],required:true}],
 'Cars':[{key:'make',label:'Make',type:'select',options:CAR_MAKES,required:true},{key:'model',label:'Model',type:'select',options:['Other'],required:true},{key:'year',label:'Year',type:'number',required:true},{key:'mileage',label:'Mileage (km)',type:'number',required:true},{key:'transmission',label:'Transmission',type:'select',options:TRANSMISSIONS,required:true},{key:'fuel',label:'Fuel type',type:'select',options:FUEL_TYPES,required:true},{key:'bodyType',label:'Body type',type:'select',options:BODY_TYPES,required:true},{key:'color',label:'Color',type:'select',options:COLORS,required:true},{key:'registered',label:'Registered car',type:'select',options:['Yes','No'],required:true},{key:'vehicleCondition',label:'Vehicle condition',type:'select',options:VEHICLE_CONDITIONS,required:true},{key:'drivetrain',label:'Drivetrain',type:'select',options:DRIVETRAINS},{key:'secondCondition',label:'Additional condition',type:'select',options:['First owner','First registration','Original parts','No faults','After crash','Engine issue','Gear issue','Need repair','Need body repair','Need repainting','Unpainted','Wiring problems']}],
 'Motorcycles & Scooters':[{key:'make',label:'Make',type:'select',options:CAR_MAKES,required:true},{key:'model',label:'Model',type:'text',required:true},{key:'year',label:'Year',type:'number',required:true},{key:'engine',label:'Engine size (cc)',type:'number',required:true},{key:'mileage',label:'Mileage (km)',type:'number'},{key:'color',label:'Color',type:'select',options:COLORS},{key:'conditionDetail',label:'Vehicle condition',type:'select',options:VEHICLE_CONDITIONS}],
 'Laptops & Computers':[{key:'brand',label:'Brand',type:'select',options:LAPTOP_BRANDS,required:true},{key:'model',label:'Model',type:'text',required:true,placeholder:'Select or enter exact model'},{key:'processor',label:'Processor',type:'select',options:PROCESSORS,required:true},{key:'ram',label:'RAM',type:'select',options:['4 GB','8 GB','16 GB','32 GB','64 GB'],required:true},{key:'storage',label:'Storage',type:'select',options:['128 GB','256 GB','512 GB','1 TB','2 TB'],required:true},{key:'screenSize',label:'Screen size',type:'select',options:SCREEN_SIZES}],
 'TV & Video':[{key:'brand',label:'Brand',type:'text',required:true},{key:'screenSize',label:'Screen size',type:'text',required:true,placeholder:'e.g. 55 inch'},{key:'resolution',label:'Resolution',type:'select',options:['HD','Full HD','4K UHD','8K','Other']},{key:'smartTv',label:'Smart TV',type:'select',options:['Yes','No'],required:true}],
 'Furniture':[{key:'material',label:'Material',type:'text',placeholder:'e.g. Leather, Mahogany'},{key:'color',label:'Color',type:'text'},{key:'dimensions',label:'Dimensions',type:'text',placeholder:'e.g. 2.4m x 0.9m'}],
 'Houses & Apartments For Rent':[{key:'propertyType',label:'Property type',type:'select',options:['House','Apartment','Flat','Room','Studio','Other'],required:true},{key:'bedrooms',label:'Bedrooms',type:'number',required:true},{key:'bathrooms',label:'Bathrooms',type:'number'},{key:'furnished',label:'Furnished',type:'select',options:['Yes','No','Partly']},{key:'rentPeriod',label:'Rent period',type:'select',options:['Per day','Per week','Per month','Per year'],required:true}],
 'Houses & Apartments For Sale':[{key:'propertyType',label:'Property type',type:'select',options:['House','Apartment','Flat','Other'],required:true},{key:'bedrooms',label:'Bedrooms',type:'number',required:true},{key:'bathrooms',label:'Bathrooms',type:'number'},{key:'landSize',label:'Land size',type:'text',placeholder:'e.g. 50 x 100 ft'}],
 'Land & Plots For Sale':[{key:'landSize',label:'Land size',type:'text',required:true,placeholder:'e.g. 50 x 100 ft'},{key:'tenure',label:'Land tenure',type:'select',options:['Mailo','Freehold','Leasehold','Customary','Other']},{key:'titleDeed',label:'Title deed available',type:'select',options:['Yes','No','In process']}],
 'Jobs':[{key:'jobType',label:'Job type',type:'select',options:['Full-time','Part-time','Contract','Temporary','Internship'],required:true},{key:'experience',label:'Experience',type:'text',placeholder:'e.g. 2 years'},{key:'salary',label:'Salary / pay',type:'text',placeholder:'e.g. UGX 800,000 monthly'},{key:'education',label:'Education level',type:'text'}],
 'Seeking Work / CVs':[{key:'profession',label:'Profession / role',type:'text',required:true,placeholder:'e.g. Accountant'},{key:'experience',label:'Experience',type:'text',required:true},{key:'education',label:'Education',type:'text'},{key:'availability',label:'Availability',type:'select',options:['Immediately','Within 1 month','Flexible']}],
 'Building & Trades':[{key:'serviceType',label:'Service type',type:'text',required:true,placeholder:'e.g. Plumbing, masonry'},{key:'serviceArea',label:'Service area',type:'text',required:true}],
 'Computer & IT Services':[{key:'serviceType',label:'Service type',type:'text',required:true},{key:'serviceArea',label:'Service area',type:'text',required:true}],
 'Repair Services':[{key:'serviceType',label:'Repair type',type:'text',required:true},{key:'serviceArea',label:'Service area',type:'text',required:true}],
 'Delivery & Logistics':[{key:'serviceType',label:'Delivery service',type:'text',required:true},{key:'serviceArea',label:'Service area',type:'text',required:true},{key:'vehicle',label:'Vehicle',type:'text'}],
 'Farm Produce':[{key:'produce',label:'Produce',type:'text',required:true,placeholder:'e.g. Maize, beans, coffee'},{key:'quantity',label:'Available quantity',type:'text',required:true},{key:'unit',label:'Unit',type:'select',options:['kg','bags','tonnes','crates','pieces','Other'],required:true}],
 'Livestock & Poultry':[{key:'animal',label:'Animal type',type:'text',required:true},{key:'quantity',label:'Quantity',type:'number'},{key:'age',label:'Age',type:'text'}],
 'Dogs':[{key:'breed',label:'Breed',type:'text',required:true},{key:'age',label:'Age',type:'text',required:true},{key:'gender',label:'Gender',type:'select',options:['Male','Female']},{key:'vaccinated',label:'Vaccinated',type:'select',options:['Yes','No']}],
};

function fieldsFor(category?:Category){if(!category)return [];return FIELD_RULES[category.name]||[];}

export default function Sell(){
 const [cats,setCats]=useState<Category[]>([]),[user,setUser]=useState<any>(null),[files,setFiles]=useState<File[]>([]);
 const [f,setF]=useState<any>({condition:'USED',city:'Kampala',negotiable:true,attributes:{}}),[rootId,setRootId]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{api('/categories').then((x:any)=>setCats(Array.isArray(x)?x:[])).catch(()=>{});const u=localStorage.getItem('minify_user');if(u)try{setUser(JSON.parse(u))}catch{}},[]);
 const root=cats.find(c=>c.id===rootId);const children=root?.children||[];
 const selectedCategory=cats.flatMap(c=>[c,...(c.children||[])]).find(c=>c.id===f.categoryId);
 const fields=useMemo(()=>fieldsFor(selectedCategory),[selectedCategory]);
 const fieldOptions=(field:Field)=>field.key==='model'&&selectedCategory?.name==='Mobile Phones'?PHONE_MODELS[f.attributes?.brand]||['Other']:field.key==='model'&&selectedCategory?.name==='Cars'?VEHICLE_MODELS[f.attributes?.make]||['Other']:field.options||[];
 const categoryLabel=selectedCategory?.name||'';
 const titlePlaceholder=categoryLabel?`e.g. ${categoryLabel==='Cars'?'Toyota Premio 2018':categoryLabel==='Laptops & Computers'?'Dell Latitude 5420':categoryLabel==='Furniture'?'6-Seater Sofa Set':categoryLabel==='Jobs'?'Experienced Accountant':categoryLabel==='Services'?'Professional Computer Repair Service':'Describe what you are offering'}`:'e.g. iPhone 15 Pro, Toyota Premio, Sofa Set, Laptop, House for Rent';
 const set=(key:string,value:any)=>setF((x:any)=>({...x,[key]:value}));
 const setAttr=(key:string,value:any)=>setF((x:any)=>({...x,attributes:{...(x.attributes||{}),[key]:value}}));
 const chooseRoot=(id:string)=>{setRootId(id);setF((x:any)=>({...x,categoryId:'',attributes:{}}));};
 const chooseCategory=(id:string)=>{setF((x:any)=>({...x,categoryId:id,attributes:{}}));};
 const chooseAttr=(key:string,value:string)=>setF((x:any)=>{const next={...(x.attributes||{}),[key]:value};if(key==='brand'||key==='make')next.model='';return {...x,attributes:next};});
 async function uploadImages(){if(!files.length)return [];const token=localStorage.getItem('minify_token')||'';const form=new FormData();files.forEach(file=>form.append('images',file));const r=await fetch(`${API}/uploads/images`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body:form});if(!r.ok)throw new Error(await r.text());return (await r.json()).images||[];}
 async function submit(e:FormEvent){e.preventDefault();if(!user){location.href='/login?next=/sell';return;}if(root?.children?.length&&!f.categoryId){setMsg('Choose a subcategory so buyers can find your advert.');return;}for(const field of fields)if(field.required&&!String(f.attributes?.[field.key]??'').trim()){setMsg(`Please fill in ${field.label}.`);return;}setBusy(true);setMsg('');
  try{if(user.role==='BUYER'){const upgraded=await api('/auth/become-seller',{method:'POST'});localStorage.setItem('minify_token',upgraded.token);localStorage.setItem('minify_user',JSON.stringify(upgraded.user));setUser(upgraded.user);}
   const imageUrls=await uploadImages();const a=await api('/ads',{method:'POST',body:JSON.stringify({...f,price:Number(f.price),negotiable:Boolean(f.negotiable),images:imageUrls})});await api(`/ads/${a.id}/publish`,{method:'POST'});setMsg('Advert submitted for review. We will make it visible after moderation.');setF({condition:'USED',region:'Central',city:'Kampala',negotiable:true,attributes:{}});setRootId('');setFiles([]);
  }catch(err:any){setMsg(err.message||'Could not submit advert.');}finally{setBusy(false);}
 }
 const qualityTitle=String(f.title||'').trim().split(/\s+/).filter(Boolean).length>=2;
 const qualityDescription=String(f.description||'').trim().length>=30;
 return <><Header/><main className="container section"><div className="panel sell-panel"><div className="eyebrow">SELL ON MINIFY MARKET</div><h1>Post an advert</h1><p className="muted">Choose a category and MINIFY will show the fields buyers need for that type of advert.</p>
 <div className="sell-category-note"><b>Category-smart advert form</b><span>Cars get vehicle details, phones get specifications, property gets property details, jobs get job details and more.</span></div>
 <form className="form" onSubmit={submit}>
  <label>What are you offering?<input required value={f.title||''} placeholder={titlePlaceholder} onChange={e=>set('title',e.target.value)}/></label>
  <div className="form-grid"><label>Main category<select required value={rootId} onChange={e=>chooseRoot(e.target.value)}><option value="">Choose a category</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
  <label>Subcategory<select required={Boolean(root?.children?.length)} disabled={!rootId||!children.length} value={f.categoryId||''} onChange={e=>chooseCategory(e.target.value)}><option value="">{rootId?(children.length?'Choose a subcategory':'This category has no subcategories'):'Choose a main category first'}</option>{children.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div>
  {categoryLabel&&<div className="sell-category-selected">Selected: <b>{root?.name}</b>{children.length?' → ':''}{children.length?categoryLabel:''}</div>}
  {fields.length>0&&<section className="category-fields"><div className="surface-head"><div><span className="eyebrow">{categoryLabel.toUpperCase()}</span><h2>Item details</h2><p className="muted">These fields are tailored to this category so buyers can compare adverts properly.</p></div></div><div className="form-grid">{fields.map(field=><label key={field.key}>{field.label}{field.type==='select'?<select required={field.required} value={f.attributes?.[field.key]||''} onChange={e=>chooseAttr(field.key,e.target.value)}><option value="">Choose {field.label.toLowerCase()}</option>{fieldOptions(field).map(o=><option key={o}>{o}</option>)}</select>:field.type==='textarea'?<textarea required={field.required} rows={4} value={f.attributes?.[field.key]||''} placeholder={field.placeholder} onChange={e=>chooseAttr(field.key,e.target.value)}/>:<input required={field.required} type={field.type} value={f.attributes?.[field.key]||''} placeholder={field.placeholder} onChange={e=>chooseAttr(field.key,e.target.value)}/>} </label>)}</div></section>}
  <div className="form-grid"><label>Price (UGX)<input required min="0" type="number" value={f.price||''} onChange={e=>set('price',e.target.value)}/></label><label>Condition<select value={f.condition} onChange={e=>set('condition',e.target.value)}><option value="NEW">Brand new</option><option value="USED">Used</option><option value="REFURBISHED">Refurbished</option></select></label></div>
  <div className="form-grid"><label>Region<select value={f.region||'Central'} onChange={e=>set('region',e.target.value)}>{REGIONS.map(x=><option key={x}>{x}</option>)}</select></label><label>District / City<select required value={f.city} onChange={e=>set('city',e.target.value)}>{DISTRICTS.map(x=><option key={x}>{x}</option>)}</select></label><label>Area / location<input value={f.location||''} placeholder="e.g. Kisementi, Ntinda, Entebbe Road" onChange={e=>set('location',e.target.value)}/></label></div>
  <label>Photos <span className="muted">(up to 8, 8MB each)</span></label><ImageUploader files={files} setFiles={setFiles}/>
  <div className="listing-quality"><b>Listing quality checklist</b><span className={files.length?'ok':''}>{files.length?'✓':'○'} Add at least one clear photo</span><span className={qualityTitle?'ok':''}>{qualityTitle?'✓':'○'} Clear advert title</span><span className={qualityDescription?'ok':''}>{qualityDescription?'✓':'○'} Useful description</span><span className={Number(f.price)>0?'ok':''}>{Number(f.price)>0?'✓':'○'} Valid asking price</span></div>
  {files.length>0&&<div className="upload-list">{files.map((x,i)=><span key={i}>{x.name}</span>)}</div>}
  <label>Description<textarea required rows={7} value={f.description||''} placeholder={categoryLabel==='Jobs'?'Describe the role, responsibilities, requirements and how to apply.':categoryLabel==='Seeking Work / CVs'?'Describe your skills, experience, preferred role and availability.':categoryLabel.includes('Rent')?'Describe the property, amenities, access, deposit and other important rental terms.':'Describe what you are offering, its condition or key details, what is included, and anything a buyer should know.'} onChange={e=>set('description',e.target.value)}/></label>
  <label className="check-row"><input type="checkbox" checked={Boolean(f.negotiable)} onChange={e=>set('negotiable',e.target.checked)}/> Price is negotiable</label>
  <button className="btn primary" disabled={busy}>{busy?'Submitting…':'Submit for review'}</button>{msg&&<div className="notice">{msg}</div>}
 </form></div></main></>;
}
