'use client';
import {useEffect,useState} from 'react';
import Header from '../components/Header';
import {api} from '../lib';

export default function Account(){
 const[u,setU]=useState<any>(null),[name,setName]=useState(''),[city,setCity]=useState(''),[current,setCurrent]=useState(''),[next,setNext]=useState(''),[confirm,setConfirm]=useState(''),[msg,setMsg]=useState(''),[passMsg,setPassMsg]=useState(''),[busy,setBusy]=useState(false),[passBusy,setPassBusy]=useState(false);
 useEffect(()=>{if(!localStorage.getItem('minify_token')){location.href='/login?next=/account';return}api('/users/me/profile').then(x=>{setU(x);setName(x.name||'');setCity(x.city||'')}).catch(()=>{})},[]);
 async function save(e:any){e.preventDefault();setBusy(true);setMsg('');try{const x=await api('/users/me/profile',{method:'PATCH',body:JSON.stringify({name,city})});setU(x);localStorage.setItem('minify_user',JSON.stringify({...JSON.parse(localStorage.getItem('minify_user')||'{}'),...x}));setMsg('Profile updated successfully.')}catch(e:any){setMsg(e?.message||'Could not update profile.')}finally{setBusy(false)}}
 async function changePassword(e:any){e.preventDefault();setPassMsg('');if(next!==confirm){setPassMsg('New passwords do not match.');return}setPassBusy(true);try{const x=await api('/auth/change-password',{method:'POST',body:JSON.stringify({currentPassword:current,newPassword:next})});setPassMsg(x.message||'Password updated successfully.');setCurrent('');setNext('');setConfirm('')}catch(e:any){setPassMsg(e?.message||'Could not update password.')}finally{setPassBusy(false)}}
 function signOut(){localStorage.removeItem('minify_token');localStorage.removeItem('minify_user');location.href='/'}
 return <><Header/><main className="container section"><div className="two"><div><section className="panel"><span className="eyebrow">MY ACCOUNT</span><h1>Profile & security</h1><p className="muted">Manage your identity and keep your MINIFY MARKET account secure.</p>{u&&<form className="auth-form" onSubmit={save}><label>Full name<input value={name} onChange={e=>setName(e.target.value)} required maxLength={100}/></label><label>Email<input value={u.email||''} disabled/></label><label>Phone<input value={u.phone||''} disabled/></label><label>City / area<input value={city} onChange={e=>setCity(e.target.value)} placeholder="Kampala" maxLength={80}/></label><button className="btn primary" disabled={busy}>{busy?'Saving…':'Save changes'}</button>{msg&&<div className="notice">{msg}</div>}</form>}</section>
<section className="panel" style={{marginTop:20}}><span className="eyebrow">SECURITY</span><h2>Change password</h2><p className="muted">Use a strong password you do not reuse on other websites.</p><form className="auth-form" onSubmit={changePassword}><label>Current password<input type="password" autoComplete="current-password" required value={current} onChange={e=>setCurrent(e.target.value)}/></label><label>New password<input type="password" autoComplete="new-password" minLength={8} maxLength={128} required value={next} onChange={e=>setNext(e.target.value)} placeholder="8–128 characters"/></label><label>Confirm new password<input type="password" autoComplete="new-password" minLength={8} maxLength={128} required value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button className="btn primary" disabled={passBusy}>{passBusy?'Updating…':'Update password'}</button>{passMsg&&<div className="notice">{passMsg}</div>}</form></section></div>
<aside className="panel"><h2>Account centre</h2>{u&&<><div className="account-summary"><strong>{u.name}</strong><span>{u.email}</span><span>{u.role==='BUYER'?'Buyer account':'Seller account'}</span></div><div className="account-links"><a className="btn outline" href="/dashboard">Dashboard</a><a className="btn outline" href="/orders">My orders</a><a className="btn outline" href="/favorites">Saved adverts</a><a className="btn outline" href="/saved-searches">Saved searches</a><a className="btn outline" href="/messages">Messages</a><a className="btn outline" href="/notifications">Notifications</a>{u.role!=='BUYER'&&<><a className="btn outline" href="/verification">Seller verification</a><a className="btn outline" href="/seller-plans">Seller plans</a></>}<button className="btn danger" onClick={signOut}>Sign out</button></div></>}</aside></div></main></>;
}
